### ISSUE TITLE
How to represent ODCRs in FOCUS

### ISSUE THREAD

**Issue by AWS-ZachErdman** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#397]
* **Maintainer Leader**: Alex
### Documents:
* [#397 ](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/397)How to represent ODCRs in FOCUS by [zserdman@amazon.com](mailto:zserdman@amazon.com)(Capacity Reservation)
* Folder: [#397-ODCR](https://drive.google.com/drive/folders/1UzTl4LBBd47g_bAY-sYqGEf6MiZuPhHe?usp=sharing)
[FOCUS OCDRs](https://docs.google.com/spreadsheets/d/1LdgZCBuV6TDehgykQ4m6AluOLE_TjX9kFxKXymXn8I4/edit?gid=1124060342#gid=1124060342)  (this document was not created inside of FOCUS workspace)
* Option 1: ~PR [#509](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/509) How to represent ODCRs in FOCUS by [zserdman@amazon.com](mailto:zserdman@amazon.com)~ DEPRACATED.
* Option 2: ~PR [#515](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/515) How to represent ODCR in FOCUS (Alternative) by [alex.hullah@gs.com](mailto:alex.hullah@gs.com)~ DEPRACATED.
* Option 3: PR [#523](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/523) Capacity Reservation Proposal for ID & Status 
* AWS: [On-Demand Capacity Reservations](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-capacity-reservations.html)
* Azure: [On-Demand Capacity Reservation](https://learn.microsoft.com/en-us/azure/virtual-machines/capacity-reservation-overview)
* Document: [How to represent ODCRs in FOCUS](https://docs.google.com/document/d/1wNKxqfqltfEFN1tdnswsNAqQUbSyXN28UAPUVbxZDpA/edit#heading=h.el7tqolosins)
* Slack: “[tf-odcr](https://f2-focus.slack.com/archives/C07GAV6UA3C)”
* Approval Deadline: ~Aug 29~, Sep 5

### Description
On-Demand Capacity Reservations (ODCRs)  ([AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-capacity-reservations.html), [Azure](https://learn.microsoft.com/en-us/azure/virtual-machines/capacity-reservation-overview)) are an important service to many AWS customers. Currently, FOCUS does not have any native fields for indicating when an ODCR was used or not used.

### Proposed approach
We suggest adding a column or adding to a column values to indicate when the line item for an ODCR represents "used" usage or "unused" usage.

### Github issue or Reference
None.

### Context
We are adding the ability to declare whether usage represents "Used" or "Unused" spend commitments. https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/382

How should this concept align with ODCRs? 

Note that: 
We may want to be able to see a separate status for both Spend commitments and ODCRs in the same line item since in [AWS you can have an SP apply to an ODCR](https://docs.aws.amazon.com/whitepapers/latest/cost-optimization-reservation-models/savings-plans.html) - perhaps for other CSPs too?

So we could have and ODCR line where the ODCR was "Unused", but an SP applied and was "Used", meaning we need both statuses.

**Comment by gparker-at-sf** [comment]
I am very interested in this discussion.

**Comment by jpradocueva** [comment]
@gparker-at-sf, I have assigned you to the ticket.

**Comment by gparker-at-sf** [comment]
Following up, reached out to set up a meeting per today's call.

**Comment by jpradocueva** [comment]
Action Items Summary:
- [ ] TF3-[#397](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/397) Riley and Zach: Prepare the groundwork for metadata correlation.
- [ ] Team: Refine the schema ID update process and consider provider versioning.
- [ ] Providers: Ensure guidelines for historical data conversion.

**Comment by AWS-ZachErdman** [comment]
1st column draft: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/tree/capacity_reservations

sample data: https://docs.google.com/spreadsheets/d/1LdgZCBuV6TDehgykQ4m6AluOLE_TjX9kFxKXymXn8I4/edit?gid=1124060342#gid=1124060342

**Comment by jpradocueva** [comment]
Action Items raised during TF-3, July 12:
- [ ] TF3-[#397](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/397) Zach: to create a pull request for the draft discussions on capacity reservations.
- [ ] TF3-[#397](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/397) Team members: to review the pull request and provide feedback, focusing on the necessity of a status column.
- [ ] TF3-[#397](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/397): George to provide examples of current capacity reservation billing records.

**Comment by jpradocueva** [comment]
Documents:
* [FOCUS ODCR](https://docs.google.com/spreadsheets/d/1LdgZCBuV6TDehgykQ4m6AluOLE_TjX9kFxKXymXn8I4/edit?gid=1124060342#gid=1124060342) 
* PR [#509](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/509)  
* AWS: [On-Demand Capacity Reservations](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-capacity-reservations.html)
* Azure: [On-Demand Capacity Reservation](https://learn.microsoft.com/en-us/azure/virtual-machines/capacity-reservation-overview)

**Comment by ahullah** [comment]
Hey Folks..... will scribble up a PR for this based on our discussions and Chris's recent suggestions im sure it wont be what we think we agreed but it will be a start ...

**Comment by shawnalpay** [comment]
Here's a backfill use case for this issue that a member of the community put forward:

> As FinOps practitioners, we want to review unused capacity reservations and their associated costs to effectively manage cloud waste and optimize resource utilization.
