### ISSUE TITLE
ConsumedQuantity and ConsumedUnit in case of 'Unused' commitment

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#492]
### Description
Currently in normative paragraphs for both ConsumedQuantity and ConsumedUnit:

> _... MUST NOT be null if ChargeCategory is "Usage" and ChargeClass not "Correction". This column MUST be null for other ChargeCategory values. ..._

We need to adjust this considering both ConsumedQuantity and ConsumedUnit MUST be null in case of ChargeCategory 'Usage' and CommitmentStatus 'Unused'. 

here is a suggestion but I'm sure we can do better :)

paragraph format:

> ._.. MUST NOT be null if ChargeCategory is "Usage", unless ChargeClass is "Correction" or CommitmentStatus is 'Unused'. This column MAY be null if ChargeCategory is "Usage" and ChargeClass is "Correction". It MUST be null if CommitmentStatus is 'Unused' or for other ChargeCategory values. ..._

bullet list format:

> - _MUST NOT be null if ChargeCategory is "Usage", unless ChargeClass is "Correction" or CommitmentStatus is 'Unused'_
> - _MAY be null if ChargeCategory is "Usage" and ChargeClass is "Correction"_
> - _MUST be null if CommitmentStatus is 'Unused' or for other ChargeCategory values_

### Issue Resources

* Discussion Documents: https://drive.google.com/drive/folders/1AwXLrINBm3rLuwielbaYr6my_7gzER0X?usp=drive_link

**Comment by jpradocueva** [comment]
TF3-[#492](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/492)  Irena to draft the necessary changes to the specification and prepare a pull request.

**Comment by marc-perreaut** [comment]
I remember we said Unused is treated as Usage in the specification. So, ConsumedUnit/Quantity should be populated also in the case of Unused Commitment.

In the case of Unused Commitment, ConsumedQuantity/Unit could be populated in the same way as PricingQuantity/Unit in the commitment Purchase record.

**Comment by jpradocueva** [comment]
TF3-[#492](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/492) Riley will comment on the issue.

**Comment by ijurica** [comment]
> I remember we said Unused is treated as Usage in the specification. So, ConsumedUnit/Quantity should be populated also in the case of Unused Commitment.
> 
> In the case of Unused Commitment, ConsumedQuantity/Unit could be populated in the same way as PricingQuantity/Unit in the commitment Purchase record: conceptually, the Unused Commitment record consumes some unused PricingQuantity/Unit.

From my perspective, Unused Commitment is the unused portion of a Purchase. If we plan to use Consumed Quantity/Unit for reporting on Unused Usage (consumable but not consumed quantity), I believe we can use it for the original Purchase as well (consumable quantity) - and we are back to **Foo Quantity** :)

**Comment by jpradocueva** [comment]
Action Item from TF-3 meeting on July 5:

- [ ] TF3-[#492](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/492) Tim O’Brien to draft a proposal outlining a structured approach for organizing issue discussions, including creating dedicated directories or repositories for each issue.

**Comment by tobrien** [comment]
@jpradocueva I submitted an Issue and PR against foundation to capture this requirement - https://github.com/FinOps-Open-Cost-and-Usage-Spec/foundation/issues/11

**Comment by jpradocueva** [comment]
### Action Items:
- [ ] TF3-[#492](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/492)  Riley: Provide comments and suggestions on the issue of handling consumed quantity and consumed units for unused credits.
- [ ] TF3-[#492](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/492)  Irena: Prepare a pull request to update the specification to address the handling of unused commitments, particularly focusing on unused credits.

**Comment by rileyjenk** [comment]
In the case of unused resource commitments such as RIs, ConsumedUnit and ConsumedQuantity should not be null, as the intent was for the unit to be representative of the commitment amount that when unused. For example if I purchase an m6g.xlarge RI and don't use it, then theses columns would represent the number of compute hours that went unused. 

Here is a link to the raw example data: https://docs.google.com/spreadsheets/d/13FdQoNtsJbqawxL0hPiTg7ZdNnHUs9goJj_tatsBtME/edit?gid=0#gid=0

For spend commitments that are time isolated, like savings plans, we need to consider how those are represented. The issues comes into view when say for that same instance it is now covered by a savings plan. if ConsumedUnit is now dollars (which it should not be), then the practitioner is now unable to sum the total number of compute hours for something like ec2 because the units are not the same thing. It would be compute hours. 

It is for this reason that we likely need to consider dedicated columns for commitment quantity column/s for providing this information. 

And the there is SAAS:

One of the principle areas that we do not support at multiple levels is where a company has a non currency unit that is purchased upfront and then "consumed" like a currency by various usage. The naming conflict is unfortunate but when a "credit", "point", "token", or "<insert whatever here>" is consumed rather than an actual currency the consumed unit wasn't really intended to be that unit. That column is intended to represent the unit that was used. 

Take for example that you do not have direct to dollars and you have credits. Say that those credits are used up by different features at different rates (e.g. https://docs.snowflake.com/en/user-guide/cost-understanding-compute). If the provider puts the consumed Unit as credits it does not reflect the usage, only the credits. If I wanted to know how many compute hours I used, I would not be able to.

It is for this reason that in the example of a made up currency unit like credits, tokes, etc... we need specific support for this scenario. We need support for expressing the purchase of those units, and their burn down.

**Comment by jpradocueva** [comment]
### Action Items from TF-3, Jul 19 call:
- [ ] TF3-[#507](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/507) PR [#507](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/507) to be put on hold.
- [ ] TF3-[#507](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/507) Chris and Irena: To lead the commitment utilization discussions and update the PR accordingly.

**Comment by AWS-ZachErdman** [comment]
I agree with Riley - you can easily remove unused consumed quantity if you don't want it included.

**Comment by ijurica** [comment]
The issue and the corresponding PR can be closed. Addressed in 1.1, in a different PR as part of Commitment Utilization
