### ISSUE TITLE
SKU Price Details

### ISSUE THREAD

**Issue by jpradocueva** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#497]
**Lead Maintainer**: Karl
### Documents: 
* [#497](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/497) SKU Price Details (Issue)
* Folder: [#497-srv-SKU-details-SKU-price-details](https://drive.google.com/drive/folders/1kbNNasX0xZBbLrcs1MQK5s5zWyv9o8CD?usp=drive_link)
* PR [#503](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/503) SKU Details + SKU PriceDetails Columns by [karl.kraft@walmart.com](mailto:karl.kraft@walmart.com) 
* PR [#530](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/530) #503a - Update SkuPriceId per SkuPriceDetails by [karl.kraft@walmart.com](mailto:karl.kraft@walmart.com) 
* Spreadsheet:[ 24.07.17-AzureEA-FOCUS-and-PriceList-sample-dataset](https://docs.google.com/spreadsheets/d/1qoy5OjFeZFIK5fuVUKGiI_yCfN5_9tBxVBaRVlBgXtA/edit?gid=240278343#gid=240278343)
* Document from Joseph:[ SKU Details from Providers](https://docs.google.com/document/d/1zPEUZ5L5wf9YAJ63ymW3tyrOFx-krJBB6sf1bHU_oOs/edit#heading=h.p2oplf92wckb)

### Description
This issue was created to host the following action item:
- [ ] TF2-[#497](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/497): Karl, Andrew: Draft SKU price details, ensuring they align with SKU price ID.
Branch: [sku-details_sku-price-details](https://github.com/kk09v/FOCUS_Spec/tree/sku-details_sku-price-details) by Karl

### Proposed approach
> Describe the approach that your group is proposing

### Github issue or Reference
> If the topic is related to a particular work item, reference the Github issue. If its a specification-wide topic, indicate that.

### Context
> Add any context that may help the community think through this and provide useful feedback

**Comment by jpradocueva** [comment]
### New set of action items:
- [ ] TF2-[#497](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/497): Karl to incorporate the discussion points into a revised document and prepare a Pull Request (PR) by next week.
- [ ] TF2-[#497](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/497):  Shawn to provide notes and feedback to Karl for the PR.
Review and approve changes to column names and issue templates in upcoming meetings.
