### ISSUE TITLE
Managing Feedback from FinOps Community to FOCUS Providers/Maintainers

### ISSUE THREAD

**Issue by robmartin33** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#498]
@robmartin33 Rob Martin is leading this issue.

### Description
When FOCUS adopters identify an issue with a FOCUS dataset, how should they communicate this to the various interested parties? Issues might include:
- Data not appearing as expected per specification in the dataset
- Use case not supported as described

The issue may indicate:
- A bug or anomaly in how data is being created by the party generating it
- A lack of understanding by the user of how the specification intends the data to be produced
- A lack of clarity or mistake in the design or documentation of the Specification
- A challenge to an existing certification of conformance with the Specification

As a result, a user-identified issues will likely need to be communicated to some combination of:
- Whoever generated the FOCUS dataset (cloud service provider or other) to have the issue corrected/diagnosed
- The FOCUS project as an issue to be investigated in documentation or design of FOCUS
- The certifying body for FOCUS Conformance Certification (Assumed at this time to be the FinOps Foundation staff)

### Proposed approach
Issue reporting by non-members of FOCUS cannot be done easily in the FOCUS_Spec repo, and there is a likelihood that misunderstandings and a large number of Use Case suggestions will come in during early release times, so for discussion purposes, the following are assumed to be required to handle the submission of issues:
- A separate repository for FOCUS Use Issues should be created and used to allow for anyone to create Issues to be investigated, not using the FOCUS_Spec repo
- FinOps Foundation Slack channel #chat-FOCUS is not an appropriate place to track reported issues
- Reported issues should be triaged prior to being published publicly by [F2 staff?]
- There is a likelihood that there may be misunderstandings among non-members more frequently early on, lowering as more organizations adopt FOCUS
- Users reporting issues should always be encouraged to also submit suspected bugs through existing support channels with their cloud service provider or other producer of FOCUS dataset (there may be an opportunity to automate a ticket, but it will always be best to use the existing relationship channels for tracking and record keeping?)
- If conformance compliance is challenged, staff will work with producers to remediate or correct
- Reported issues that are confirmed should be publicly visible for practitioners and potential adopters to understand
- There would be value in producers being involved in the conversation on the Issue to document expected resolution times, to proactively publish known bugs or discrepancies on the roadmap, and to see what is being reported and identified

Someone adopting FOCUS who is a Member may open an issue in the FOCUS_Spec if they wish. 

### Github issue or Reference
> If the topic is related to a particular work item, reference the Github issue. If its a specification-wide topic, indicate that.

### Context
This issue was raised at the 5 July 2024 Task Force 3 meeting by Alex Hullah

There is a strong correlation between this issue's resolution and the establishment of a FOCUS Conformance Compliance program which the SteerCo will discuss in detail at the 25 July 2024 monthly meeting.

**Comment by jpradocueva** [comment]
Action Items from TF-3 meeting on July 5:
- [ ] TF3-[#498](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/498) Rob: Provide an overview of how this fits with the conformance and certification planning and report back in the next meeting.
- [ ] TF3-[#498](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/498)  Joaquin: Set up the repository and define the process for issue submission and management

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on July 8:
- [ ] Maintainer-[#498](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/498) Rob: To get technical details for the new repository implementation.

**Comment by ahullah** [comment]
Thanks for this Rob... This is exactly what I was looking for so we don't all go off and raise many many duplicate support requests to the billing generators

**Comment by jpradocueva** [comment]
Action Items raised during TF-3 call on Friday, July 12:
- [ ] TF-3-[#498](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/498) Rob: Present the plan to the FinOps Foundation board and socialize internally for support.
- [ ] TF-3-[#498](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/498) FinOps Foundation Staff: Set up the new repository and triage system, aiming for implementation starting in August.
- [ ] TF-3-[#498](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/498) Joaquin: Assist to finalize documentation and drawings for the proposed solution.
- [ ] TF-3-[#498](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/498) All Members: Review the presented plan and provide feedback before the next meeting.

**Comment by shawnalpay** [comment]
@robmartin33 @mike-finopsorg Do you believe that, with the creation of the FOCUS User Group and associated calls, we have solved sufficiently for this to close this issue?

**Comment by shawnalpay** [comment]
Discussed in Oct 15 TF1 call.  @robmartin33 agreed we can close this issue.

**Comment by jpradocueva** [comment]
### TF-2 call on Oct 15:
Topic: [#498](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/498) Managing feedback from FinOps community to focus providers/maintainers
Discussion Summary: This item was raised to manage how feedback from the FinOps community should be handled by the focus providers and maintainers. It was noted that a focus user group now exists, addressing the concerns that had been raised in this issue.
Resolution: The team agreed to close this issue as the focus group had successfully addressed the feedback management process.
