### ISSUE TITLE
Service Type

### ISSUE THREAD

**Issue by jpradocueva** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#502]
### Description

It is clear that we need to expand Service Classification by introducing further breakdowns. To this end, we have already started discussing the Service Subcategory. Based on previous discussions that normalized FOCUS columns used for classification are usually accompanied by provider-specific columns serving similar purposes (e.g., SKU Category, SKU Type), I suggest we **introduce a Service Type column** to be used for service classification using provider-specific values.

Even if we don't manage to specify the service subcategory in time (as part of FOCUS 1.1), the Service Type column would still provide the necessary service classification breakdown as a provider-specific column.

### Proposed approach

I suggest we **introduce a Service Type column** to be used for service classification using provider-specific values.

Although there might not be an appropriate native provider column in the datasets that we could map to this column, all providers already classify their services on their web pages.

**Note:** According to current providers' service classifications, a service can be associated with multiple Service Types (many-to-many). It is important to note that introducing a Service Type column would require each service to be associated with only one Service Type, establishing a strict hierarchical relationship (one-to-many).

### Github issue or Reference

- https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/404

**Comment by cnharris10** [comment]
Example of GCP subtypes 
<img width="469" alt="image" src="https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/assets/17853509/e89cbe53-151d-4a5e-9db9-4e8bcd02e93e">

**Comment by jpradocueva** [comment]
### Action Items from TF-1, July 9 call:
- [ ] TF-2-[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Chris, Janine: Volunteer and reach out to providers (Rupa, Michael, Zach Aaron) for feedback on service classification.
- [ ] TF-2-[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Janine: Catalog services for AWS and Azure and reach out to other team members for GCP data.
- [ ] TF-2-[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Chris: To share Google Cloud API categorization with Janine as a potential starting point for GCP.

**Comment by rileyjenk** [comment]
@jpradocueva can we close this issue as it was split up into many.

**Comment by jpradocueva** [comment]
@rileyjenk, ok, I am closing the issue and adding the latest update from the Maintainers call:

[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Service Type
Maintainer: Irena
Documents:
[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Service Type
Folder:[ #502-srv-type](https://drive.google.com/drive/u/0/folders/1rD6aCkDQbo6X_M3dF30eZHMJyThhThil)
Spreadsheet:[ Taxonomy](https://docs.google.com/spreadsheets/d/1S9f3T3V9k6IYScoI06NG3cFvadkkvAvR/edit?usp=drive_link&ouid=112877381987597732783&rtpof=true&sd=true)
Document:[ Service Type Dimension](https://docs.google.com/document/d/1Ejr38UXBjmzttGiFQFyM6khZu6fCV378yG4nDZXgSBw/edit?usp=drive_link)
Owner: Irena/Janine
Status: Parked for post v1.1.
Summary: The service type issue overlaps with the existing service category, which already provides sufficient classification. Therefore, it was decided to address this issue after the v1.1 release.
Next Steps: None required for v1.1.
Action Items: None for v1.1.
Pending Action Items:
TF1-[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Chris, Janine: Volunteer and reach out to providers (Rupa, Michael, Zach Aaron) for feedback on service classification. PENDING
TF1-[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Janine: Catalog services for AWS and Azure and reach out to other team members for GCP data. PENDING
TF1-[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Chris: To share Google Cloud API categorization with Janine as a potential starting point for GCP. PENDING
TF1-[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Janine: to provide additional examples and update the document.
TF1-[#502](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/502) Irena and Janine: to reach out to providers for their categorizations.
