### ISSUE TITLE
Expose a CommitmentDiscountUnitPrice and a CommitmentDiscountCost column to expose its unit price and cost to compare against List and Contracted unit rates/costs.

### ISSUE THREAD

**Issue by cnharris10** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#534]
Exposing a commitment discount unit price and cost allows customers to determine whether the effective cost was solely determined by the committed rate or combined with possibly additional discounts. For customers with high commitment discount coverage, this commitment discount unit price and cost information is more useful for forecasting future costs than list or contracted cost/unit prices since these services majority of eligible services are being charged at these committed rates. 

Currently:

1. When a commitment discount covers a resource, its unit price is not exposed by default.

2. A contracted discount can also apply to a commitment discount rate, so showing neither makes deriving the original commitment discount rate, and its additional savings, impossible.

**Comment by ijurica** [comment]
Considering we don’t know which price reductions EffectiveCost might encompass besides non-negotiated commitment-based discounts (such as RI or Savings Plans), I completely agree that this is valuable information.

As far as I know, it’s not specified whether the non-negotiated burn-down commitment-based discounts are applied before or after other potential discounts, and I believe we should clarify this as well. I assume non-negotiated burn-down commitment-based discounts should be applied directly to the Contracted [UnitPrice|Cost], but we still need to discuss it.

Regarding Example 2, I expected the following values:

-  CommitmentCost = 0.1538 (inclusive of negotiated discounts and non-negotiated commitment-based discounts, if present, while excluding negotiated commitment discounts or any other discounts)
- EffectiveCost = 0.112304 (inclusive of all discounts)

**Comment by jpradocueva** [comment]
### Summary TF-2 call on Oct 16:
[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534) Expose CommitmentDiscountUnitPrice and CommitmentDiscountCost Columns
Key Discussion Items: The group discussed the importance of exposing the effective cost or unit price of a commitment-based discount to compare it against list prices.
Problem Identification: The current specification does not allow for a clear comparison of list, contracted, and discounted prices.
Divergent Views: Some participants had differing views on whether the current example provided was clear, and they requested further clarification.
Final Agreement: The issue was considered important enough to create a work item for, with some minor clarifications required.
Action Items: 
[TF-2-[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Chris, @cnharris10  will be responsible for creating a work item and addressing follow-up comments.

**Comment by cnharris10** [comment]
> Considering we don’t know which price reductions EffectiveCost might encompass besides non-negotiated commitment-based discounts (such as RI or Savings Plans), I completely agree that this is valuable information.
> 
> As far as I know, it’s not specified whether the non-negotiated burn-down commitment-based discounts are applied before or after other potential discounts, and I believe we should clarify this as well. I assume non-negotiated burn-down commitment-based discounts should be applied directly to the Contracted [UnitPrice|Cost], but we still need to discuss it.
> 
> Regarding Example 2, I expected the following values:
> 
> * CommitmentCost = 0.1538 (inclusive of negotiated discounts and non-negotiated commitment-based discounts, if present, while excluding negotiated commitment discounts or any other discounts)
> * EffectiveCost = 0.112304 (inclusive of all discounts)

Thanks @ijurica, this was not indicated correctly and has been corrected above.

**Comment by cnharris10** [comment]
Linking issue #298 as a related issue.  

Issue #298, raised by @jaxwilson calls out the need for FOCUS to be able to calculate the Estimated Savings Rate (ESR).  With this issue proposing to add `CommitmentDiscount{Cost,UnitPrice}` columns, this would allow practitioners to forecast ESR with known `Contracted{Cost,UnitPrice}` further reduced by `CommitmentDiscount{Cost,UnitPrice}` values.

For example, for an m5.2xlarge costing `$0.384` in US-EAST-1, the reduced rate for a 3-year, Partial Upfront RI is `$0.1538`.  If a practitioner gets an additional 20% off, then this would be viewed as:

```
PricingQuantity: 1
ListCost: $0.384
ListUnitPrice: $0.384
ContractedCost: $0.3072
ContractedUnitPrice: $0.3072 ($0.384 * 0.8) 
CommitmentDiscountCost: $0.1538 
CommitmentDiscountUnitPrice: $0.1538
```

ESR is: `CommitmentDiscountUnitRate` - (`ListUnitRate` - `ContractedUnitRate`) / `ListUnitRate`

**Comment by jpradocueva** [comment]
### Summary of the Task Force 3 call on Oct 18:
[#298](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/298) Discussion
Key Discussion Items: Review of work item #298, related to ESR (Estimated Savings Rate) SQL queries and use cases.
Problem Identification: Users need a reliable ESR calculation, but there are multiple variations of the SQL query, leading to discrepancies.
Divergent Views: Discussion on whether service names should be included in the SQL and whether the focus should be on a single unified calculation method.
Final Agreement: The group will finalize the SQL query and validate it with stakeholders. If this is achieved, we can close this Issue.
Action Items: 
- [ ] Chris, @cnharris10  will refine SQL queries and ensure alignment with other related work items ([#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)). Jackie will review the proposed SQL.

**Comment by shawnalpay** [comment]
@cnharris10 Could you please add a succinct use case for this one?

**Comment by cnharris10** [comment]
@shawnalpay 

As a practitioner supporting a business with a high coverage rate (80%+), I want to examine my existing infrastructure and base projections off the most accurate committed rate possible.

Most simple example:
1 m5.2xlarge has a list cost of `$0.384`, and a reduced rate of `$0.282` with a 1-year, no upfront savings plan.  My List and Contracted Unit Rates both show `$0.384`.  Currently, I can only rely on EffectiveCost to forecast costs, but this may have additional discounts that may change across billing periods.

In order to forecast on the committed rate deterministically, it must be included within the dataset.

**Comment by smokemonster99** [comment]
As a practitioner I like this for the additional benefit of allowing **auditing** of Commitment Discounts we expect to be receiving.

**Comment by jpradocueva** [comment]
### Notes from the Maintainers' call on November 4:
**Context:** This task involves making commitment discounts transparent by showing discounted prices and effective costs, which allows practitioners to measure savings from Reserved Instances, Savings Plans, and similar commitment models.
**Level of Effort Required:** Medium — Exposing commitment pricing is straightforward but requires consistent data presentation across providers.
**Level of Impact:** High – Showing discounted prices and effective costs for commitments (such as Reserved Instances) enables practitioners to better assess savings, supporting informed financial planning and commitment utilization strategies.

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on Nov 25:
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Chris @cnharris10 : Refine the [#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534) proposal to include detailed guidance on column definitions and effective cost breakdowns.
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Task Force 2: Incorporate [#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534) discussions into SaaS MVP decomposition to ensure consistency.
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] All members: Review the proposed columns and provide feedback on feasibility and implementation strategy.
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Shawn @shawnalpay : Notify the Steering Committee of the addition of this new Work Item, [#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534).

**Comment by cnharris10** [comment]
I've taken the dataset produced for proposing `CommitmentDiscount{Quantity,Unit}` from v1.1 and added a proposal for `CommitmentDiscount{UnitRate,Cost}` for v1.2 in this [sheet](https://docs.google.com/spreadsheets/d/1AYDPZ4rl90PPEbyQJUaGCUSwZ4s_sfy-8sO2KyNq0aM/edit?pli=1&gid=1712247049#gid=1712247049).  See the blue columns.

Guiding Principles:
- `CommitmentDiscountCost` = `PricingQuantity * CommitmentDiscountUnitRate`
- `CommitmentDiscountUnitRate`
    - Usage-based Commitment Discounts (i.e. Reserved Instances, Committed-Use Discounts) require a chosen, eligible SKU upfront (i.e. m5.2xlarge for AWS)
        - **Purchase Rows** - The `CommitmentDiscountUnitRate` is the discounted rate, derived as the commitment discount's term length (i.e. usually 1 or 3 years) divided by the total, aggregate purchase total (i.e. for a no upfront, aggregate of 12 or 36 months of purchases).
        - **Usage Rows** - The `CommitmentDiscountUnitRate` is the discounted unit rate of the covered resource for that charge period determined by the provider heuristic.
            - In the case of commitment flexibility, the `CommitmentDiscountRate` is derived as commitment discount's purchase total multiplied by the commitment flexibility coefficient, and the `PricingQuantity` must be adjusted to ensure the correct total.
    - Spend-based Commitment Discounts (i.e Savings Plans, Flexible Committed-Use Discounts) require an interval (i.e. hourly) committed, monetary total
        - **Purchase Rows** - The `CommitmentDiscountUnitRate` is derived as the monetary value committed for each interval (i.e. hourly).
        - **Usage Rows** - The `CommitmentDiscountUnitRate` is the discounted unit rate of the covered resource for that charge period determined by the provider heuristic.

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on December 9:
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Chris @cnharris10 to refine and share the extended sheet on commitment discount pricing for member review.
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Chris @cnharris10 to provide a guided walkthrough of the spreadsheet for interested members.
- [ ] [[#534]](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534) All members to review the spreadsheet and provide comments on the proposed columns.

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on December 16:
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Chris @cnharris10 : Create and present a one-pager document clearly outlining the flexible calculation methodology for commitment discounts.

**Comment by jpradocueva** [comment]
### Action Items from the TF-3 call on December 20:
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Shawn @shawnalpay : Get clarity on what the SKU represents.
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Shawn: @shawnalpay  Suggested to take this discussion to TF-2 for Cloud Providers input (tight the language for SKU? #314)
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Irena @shawnalpay : to analyze savings calculations for these two options (A & B See [spreadsheet](https://docs.google.com/spreadsheets/d/1AYDPZ4rl90PPEbyQJUaGCUSwZ4s_sfy-8sO2KyNq0aM/edit?usp=drive_link))

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' meeting on Jan 6:
- [ ] [#534] Irena - Prepare additional sample data illustrating different scenarios for commitment discount application.
- [ ] [#534] Shawn - to kick off a discussion about this topic ahead of next week’s Maintainers meeting minutes

**Comment by jpradocueva** [comment]
### Action Items from Members' call on Jan 9:
- [ ] [#534] Chris @cnharris10 - Finalize the PR draft for Commitment Discount Cost & Unit Price.
- [ ] [#534] Irena @ijurica  - Analyze data modeling to ensure pricing adjustments correctly reflect commitment discount flexibility.
- [ ] [#534] Shawn - Bring SKU ID concerns to the Maintainers Meeting for alignment.

**Comment by jpradocueva** [comment]
### Action Items from TF-3 call on Jan 10:
- [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Chris @cnharris10 : will find a FOCUS members interesting in the topic to start drafting the PR based on the document
       - Larry suggested Possibly Andrew Quigley from northwesternmutual
 - [ ] [[#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534)] Irena @ijurica : will clean up the document based on the discussion (no two options) and will add comment to the work item.

**Comment by ijurica** [comment]
Through further analysis of the Option A sample data (available [here](https://docs.google.com/spreadsheets/d/1AYDPZ4rl90PPEbyQJUaGCUSwZ4s_sfy-8sO2KyNq0aM/edit?pli=1&gid=1712247049#gid=1712247049)) and offline discussions, some discrepancies in the sample data related to Committed Usage with size flexibility were identified  For example: 
- The unused usage record reflected the SKU-related data of the running resource instead of the RI. 
- The charge for the portion of the cost not covered by the commitment (i.e., PricingCategory: Standard) was missing.

Combined with an ambiguously worded sentence in the description of how Commitment Size Flexibility applies to Committed Usage records, these discrepancies led to misinterpretations. 

The issues in the sample data for Option A have been resolved, and it now appears that both [option A](https://docs.google.com/spreadsheets/d/1AYDPZ4rl90PPEbyQJUaGCUSwZ4s_sfy-8sO2KyNq0aM/edit?pli=1&gid=1712247049#gid=1712247049) and [option B](https://docs.google.com/spreadsheets/d/1AYDPZ4rl90PPEbyQJUaGCUSwZ4s_sfy-8sO2KyNq0aM/edit?pli=1&gid=1317730356#gid=1317730356) describe the same basic concept.

**Comment by aws-letianfeng** [comment]
I would prefer this to be solved through the concept of amortization. Commitment Discount Unit Price is essentially the pre-discounted amortized cost of Reserved Instances and Savings Plans. The after discount amortized cost is defined as Effective Cost today. We just need a pre-discount version of it.

**Comment by shawnalpay** [comment]
> I would prefer this to be solved through the concept of amortization. Commitment Discount Unit Price is essentially the pre-discounted amortized cost of Reserved Instances and Savings Plans. The after discount amortized cost is defined as Effective Cost today. We just need a pre-discount version of it.

It would be helpful for you to review PR #699 and provide approval or request changes.  We will also be discussing this WI / PR in TF1 next Tuesday, and it would be helpful if you attended to provide perspective.

**Comment by shawnalpay** [comment]
Moving out of scope of 1.2, given that we lacked consensus and wished to prioritize other initiatives.  Will add it into 1.3 consideration.

**Comment by Matt-Cowsert** [comment]
We have not been able to get traction on #961 or #1384, two different approaches to supporting this request. Because this request has evolved so much from its initial request, I'm closing (limited utility in retaining). If we chose to pursue this , we can always refer back to this work item for historical context.
