### ISSUE TITLE
[Work_Item] (BUG) Ensure all user-defined Tags are encapsulated within the `Tags` column

### ISSUE THREAD

**Issue by cnharris10** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#540]
## 1. **Problem Statement** *

> What is the problem?: Explain the context and why it needs resolution.
> Impact: Describe how the problem affects users, systems, or the project.
> 
In a recent discussion with @AWS-ZachErdman, he mentioned an oversight within the Tags column that at least affects providers with 2+ user-defined tags systems. In this case, AWS (user-defined resource tags, cost categories) and GCP (tags, labels) are affected.
 
The Tags column currently says: Providers MUST NOT alter user-defined Tag keys or values. In cases where a provider has multiple user-defined tagging features that allow for the same user-defined tags to be created, but partitioned by feature, this will require at least N-1 user-defined features to require some prefix in order to prevent clobbering.
 
For example, AWS has user-defined both resource tags and user-defined cost categories. If a customer defines a user-defined resource tag as foo:bar and a cost category as foo:baz, then persisting both in the Tags column key/value map will cause clobbering (i.e. either "bar" or "baz" will persist, not both). The same case can occur between GCP tags and labels.

## **Use Case(s)**
NA

## 2. **Objective** *

> State the objective of this work item. What outcome is expected?
> Success Criteria: Define how success will be measured (e.g. metrics and KPIs).

All user-based or provider-based tags are encapsulated within the `Tags` column with predefined prefixes preventing clobbering for at least N-1 tagging schemes.

## 3. **Supporting Documentation** *

> Include links to supporting documents such as:
> - Data Examples: [Link to data or relevant files; DO NOT share proprietary information]
> - Related Use Cases or Discussion Documents: [Link to discussion]
> - PRs or Other References: [Link to relevant references]
 
Original Tags column definition for FOCUS 1.0: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/227
Use Case: Analyze cost and usage by multiple tag structures without guessing which columns contain various tags

## 4. **Proposed Solution / Approach**

> Outline any proposed solutions, approaches, or potential paths forward. Do not submit detailed solutions; please keep suggestions high-level.
> 
> Initial Ideas: Describe potential solution paths, tools, or technologies.
> Considerations: Include any constraints, dependencies, or risks.
> Feasibility: Include any information that helps quantify feasibility, such as perceived level of effort to augment the spec, or existing fields in current data generator exports.
> Benchmarks: Are there established best practices for solving this problem available to practitioners today (e.g. mappings from existing CSP exports that are widely used)?

In the proposed approach, using the AWS CUR as an example, the following tags are considered:
 
User-defined Tags:
- Resource tag: `foo:bar` (i.e. `resourceTags/user:foo` with value `bar`)
- Cost Category tag: `foo:bar3` (i.e. `costCategories/foo` with value `bar3`)
 
Provider-defined Tag:
- System-defined Tag: `foo:bar2` (i.e. `resourceTags/aws:foo` with value `bar2`)

The proposal is to amend the `Tags` column to allow a user-defined prefix to be concatenated with a finalized user-defined tag key for N-1 user-defined tagging schemes.  This allows for 1 tagging scheme to remain without a user-defined `prefix`, so practitioners can reference a user-defined tagging schema without a prefix.
 
With the tags supplied above, all `Tags` can be co-located as either:

**Option 1: Predefined prefix declared for N-1 user-defined and all provider tags**
Provider declares prefix: `costCategories` for user-defined cost category tags and `aws` for provider-defined system tags.
 
`Tags: { "foo": "bar", "aws:foo": "bar2", "costCategories:foo": "bar3" }`
 
**Option 2: Prefix declared for all user-defined and all provider tags**
Provider declares prefix `user` for user-defined resource tags, prefix: `costCategories` for user-defined cost category tags, and `aws` for provider-defined system tags.
 
`Tags: { "user:foo": "bar", "aws:foo": "bar2", "costCategories:foo": "bar3" }`

## 5. **Epic or Theme Association**
> This section will be completed by the Maintainers.
>
> Epic: [Epic Name]
> Theme: [Theme Name, if applicable]

TBD

## 6. **Stakeholders** *
> List the main stakeholders for this issue.
>
> Primary Stakeholders: [Name/Role]
> Other Involved Parties: [Names/Roles]

TBD

**Comment by jpradocueva** [comment]
### Summary TF-2 call on Oct 16:
[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540) [DISCUSSION]: Tags Column Definition and User-Defined Tags
Key Discussion Items: The discussion focused on the requirement that user-defined tags cannot be altered, which could lead to issues with normalization and denormalization.
Problem Identification: Some cloud providers (AWS, specifically) have multiple tag schemes, leading to complications in enforcing a strict tag policy.
Divergent Views: The group debated whether changing the definition would introduce a breaking change.
Final Agreement: Chris will create a work item to formalize the issue, advocating for a potential change in the 1.2 release.
Action Items: 
[TF-2-[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Chris, @cnharris10  will handle creating the work item for this issue.

**Comment by jpradocueva** [comment]
### Summary from Members' call on Oct 17:
[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540) [DISCUSSION]: Tags Column Definition Mandates that User-Defined Tags are Not Altered, Which Can Lead to Various Scenarios
Primary Issue: This discussion revolves around the current requirement in the specification that user-defined tags must not be altered. The concern is that this rule could lead to complications when practitioners deal with multiple user-defined tag schemes from different providers.
Core Problem: AWS, for instance, allows both user-defined resource tags and user-defined cost categories, which could result in conflicts when both types of tags share the same key names. The current specification does not adequately address how to differentiate these multiple tag schemes without altering the user-defined tags.
Divergent Views: Some members felt that allowing providers to prepend a prefix to user-defined tags could resolve the issue without altering the tags themselves, while others expressed concern that introducing prefixes would increase complexity and make tag management harder for practitioners. There was also debate about whether this could be considered a breaking change.
Final Agreement: The group agreed to explore solutions that would allow providers to prepend a prefix for certain user-defined tag schemes (e.g., cost categories) without altering other user-defined tags. This Issue #540 represents the first “work item” to prepare. However, this should be carefully reviewed to ensure that it doesn’t introduce complexity or conflicts for practitioners. This Issue #540 represents the first “work item” to be prepared by the group.
Action Items:
- [ ] [Members-[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Chris @cnharris10 : Draft a proposal for handling multiple user-defined tag schemes without altering tags, including the use of prefixes where appropriate. 
- [ ] [Members-[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Chris @cnharris10 : Review the potential impact of this proposal to determine if it constitutes a breaking change.

**Comment by thecloudman** [comment]
I use GCP and Azure and in GCP we have labels and tags, in both labels and tags we have some matching keys. In our FOCUS dataset we dont have any issues in showing the key values from both labels and tags. Might need to do some more investigation into this one.

**Comment by shawnalpay** [comment]
@thecloudman Interesting; thanks for sharing.

@cnharris10 @AWS-ZachErdman Do we have real-world examples of this happening, and if so, could you share?  It may be difficult to get the stakeholders to prioritize this one if it's not perceived to be a problem.

**Comment by cnharris10** [comment]
@shawnalpay 
AWS: https://docs.aws.amazon.com/cur/latest/userguide/table-dictionary-focus-1-0-aws.html#:~:text=The%20FOCUS%201.0,website. (i.e. `AWS_CostCategories`)

**Comment by cnharris10** [comment]
@thecloudman

A couple questions:

1. For GCP exports, are you saying that when you have a tag, `foo:bar`, and a label: `foo:baz`, you are fine with (non-deterministically) the `Tags` column manifesting as either `{"foo": "bar"}` +or_ `{"foo": "baz"}` and losing either the label or tag?

2. AWS is working around this clobbering issue by keeping user-defined resource tags within the `Tags` column and then creating a provider-defined column, `AWS_CostCategories`, with their other user-defined tags column.  If providers follow this approach, then unioning N provider's data will produce 1 `Tags` column and then a bunch of provider-defined columns for other user-defined tags.  Is this approach acceptable to you?

Example with 3 hypothetical providers: Provider1, Provider2, Provider3
- `Tags: { ... }`
- `x_Provider1OtherUserDefinedTags: { ... }`
- `x_Provider2OtherUserDefinedTags: { ... }`
- `x_Provider3OtherUserDefinedTags: { ... }`

**Comment by rileyjenk** [comment]
I just tested this with our own data and there is potential collision if their a multiple mechanisms that are resulting in keys that are the same. In the event that the provider has a multiple systems that provide key and values in the tags column then they either need to:
- (Provider) prevent collisions on entry (pretty large scope here but could be possible)
- (Provider) pick a winner (problematic)
- (Spec) As is above the spec allows for keys to be prepending with a context of the key to prevent collisions.

**Comment by udam-f2** [comment]
I also see the need for this.

The spec allowing for namespacing to avoid these collisions seems like the preferable approach here.

**Comment by ijurica** [comment]
An oversight in the specification, and we need to resolve it.

**Comment by jpradocueva** [comment]
### Notes from the Maintainers' call on November 4:
**Context:** Practitioners face challenges in tracking resources due to overlaps in tagging structures across providers. This work item seeks to address inconsistencies and potential conflicts in tags by standardizing guidance on user-defined tags.
**Level of Effort Required:** Low — Addressing the tagging structure is manageable but may require coordination with providers to align on consistent tagging practices.

**Comment by daviddinhgcp** [comment]
We don't have this problem in GCP as label keys and tag keys must be unique.  In the billing data, tags and labels have separate columns or fields.  Although, one could have the same key for labels and tags and assigned to the same resource.  It would be accurately reflected in the respective columns.  GCP also doesn't have a particular set of schema for tags and labels.  GCP aslo uses system labels, these are auto generated metadata that applies to certain resources.  System labels are also reported in separate columns.

**Comment by cnharris10** [comment]
> We don't have this problem in GCP as label keys and tag keys must be unique.  In the billing data, tags and labels have separate columns or fields.  Although, one could have the same key for labels and tags and assigned to the same resource.  It would be accurately reflected in the respective columns.  GCP also doesn't have a particular set of schema for tags and labels.  GCP aslo uses system labels, these are auto generated metadata that applies to certain resources.  System labels are also reported in separate columns.  

Thanks @daviddinhgcp for the added context. For tags/labels, since keys can be the same and Tags is effectively a Map data type, we'll need a way to differentiate - likely allowing prefixes for user-generated k/v pairs. 

For system labels, these are "provider" tags, and the guidance is to add a provider-provided prefix to these k/v pairs to ensure no clobbering

**Comment by thecloudman** [comment]
Another option - organisations who leverage 2+ tagging schemes should have a tagging standard which defines the key values for each type of tag. For example in Google, they have labels and tags that can be user defined. Labels are the same as tags in azure but tags in gcp are used for automation or assigning policies etc to resources. Therefore, an organisation should have a tagging standard that defines the difference between the two types and clearly outlines the requirements of the two types. Providers must not prefix user defined tags or labels. Providers Must prefix provider defined tags and labels

**Comment by jpradocueva** [comment]
### Action Items from the Members' call on December 5:
- [ ] [[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Chris @cnharris10 : Aggregate poll results and provide a recommendation for addressing the encapsulation bug based on group feedback.
- [ ] [[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Volunteer: Document examples of current user-defined tag conflicts for inclusion in the resolution proposal.
- [ ] [[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Irena @ijurica : Draft a proposal outlining the phased approach, ensuring backward compatibility for existing implementations.
- [ ] [[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] All members: Review and comment on the proposed phased approach before the next meeting.

**Comment by timwright2000** [comment]
> > We don't have this problem in GCP as label keys and tag keys must be unique.  In the billing data, tags and labels have separate columns or fields.  Although, one could have the same key for labels and tags and assigned to the same resource.  It would be accurately reflected in the respective columns.  GCP also doesn't have a particular set of schema for tags and labels.  GCP aslo uses system labels, these are auto generated metadata that applies to certain resources.  System labels are also reported in separate columns.
> 
> Thanks @daviddinhgcp for the added context. For tags/labels, since keys can be the same and Tags is effectively a Map data type, we'll need a way to differentiate - likely allowing prefixes for user-generated k/v pairs.
> 
> For system labels, these are "provider" tags, and the guidance is to add a provider-provided prefix to these k/v pairs to ensure no clobbering

@cnharris10 sorry cant tell if you are saying you think we may still have an issue with the Google tags and labels data for some reason? Perhaps we could have collisions across labels and tags (even though labels have to be unique wrt other labels and tags have to be unique wrt other tags) ? or something else? don't the prefixes take care of this?

**Comment by cnharris10** [comment]
> > > We don't have this problem in GCP as label keys and tag keys must be unique.  In the billing data, tags and labels have separate columns or fields.  Although, one could have the same key for labels and tags and assigned to the same resource.  It would be accurately reflected in the respective columns.  GCP also doesn't have a particular set of schema for tags and labels.  GCP aslo uses system labels, these are auto generated metadata that applies to certain resources.  System labels are also reported in separate columns.
> 
> > 
> 
> > Thanks @daviddinhgcp for the added context. For tags/labels, since keys can be the same and Tags is effectively a Map data type, we'll need a way to differentiate - likely allowing prefixes for user-generated k/v pairs.
> 
> > 
> 
> > For system labels, these are "provider" tags, and the guidance is to add a provider-provided prefix to these k/v pairs to ensure no clobbering
> 
> 
> 
> @cnharris10 sorry cant tell if you are saying you think we may still have an issue with the Google tags and labels data for some reason? Perhaps we could have collisions across labels and tags (even though labels have to be unique wrt other labels and tags have to be unique wrt other tags) ? or something else? don't the prefixes take care of this? 

Because tags and labels are user-defined and the current guidance says that no user-defined FOCUS tags cannot contain a prefix to namespace collisions. the problem exists within GCP.

**Comment by timwright2000** [comment]
@cnharris10 still getting stuck here.... for GCP, user entered labels are unique, user entered tags are unique... may be easier to discuss live...

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on December 16:
- [ ] [[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Chris @cnharris10 : to review feedback on poll options in TF1, see if we can align on prevailing option; if we get alignment, then we can move forward on PR

**Comment by jpradocueva** [comment]
### Action Items from the TF-1 meeting on December 17:
- [ ] [[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Chris @cnharris10 : Follow up with Graham to clarify and document the fourth proposed solution.
- [ ] [[#540]](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540) Tim @timwright2000 : Bring GCP sample data showing its current implementation of tags.
- [ ] [[#540]](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540) Tim @timwright2000 : to prepare an issue in the backlog indicating an alternative path forward to the current solution.
- [ ] [[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Group: Discuss poll results and pros/cons of each option in a shared document.
- [ ] [[#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540)] Shawn @shawnalpay : Explore ways to increase engagement on future polls.

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on Jan 6:
[#540] Chris: Continue driving the resolution of the user-defined tag encapsulation issue, ensuring the proper placement of all tags within the "tags" column. Provide updates on progress in the next scheduled meeting.

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on Jan 6:
[#540] Chris: Update the PR draft to enforce tag encapsulation within the Tags column.
Previous Action items assigned to Tim Wright (Google):
[#540] Tim: to prepare an Issue in the backlog indicating an alternative path forward to the current one. 
[#540] Tim: to bring sample data to see how GCP resolves this issue

**Comment by jpradocueva** [comment]
### Action Items from Members' call on Jan 9:
- [ ] [#540] Chris  @cnharris10 - Continue engaging with the user group to clarify the reasoning behind votes and encourage discussion.
- [ ] [#540] Tim Wright  @timwright2000 - Provide an update on the alternative approach he explored over the holidays.
- [ ] [#540] Chris @cnharris10 - Prepare for a final decision in the next TF1 meeting to enable PR submission.

**Comment by cnharris10** [comment]
Today in TF-1, we closed this poll to amend the Tags definition based on issue [#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540).  The results aggregated across both the FinOps and FOCUS slack channels overwhelmingly favored Option 3 :large_green_circle:, and we will be moving forward with this option to amend the Tags definition.  Thank you to everyone who voted and participated in any discussions!

<img width="1547" alt="image" src="https://github.com/user-attachments/assets/28de955a-08f3-414f-a1e4-edac138493d4" />

**Comment by aws-letianfeng** [comment]
AWS allows tag keys to contain "/". The FOCUS specification requires "Providers MUST NOT alter user-defined Tag keys or values."

What is the expected behavior under option 3 when a customer specifies a resource tag as "costCategory/key1 : value1", while the customer also has key1 as an AWS Cost Category?

> Today in TF-1, we closed this poll to amend the Tags definition based on issue [#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540). The results aggregated across both the FinOps and FOCUS slack channels overwhelmingly favored Option 3 :large_green_circle:, and we will be moving forward with this option to amend the Tags definition. Thank you to everyone who voted and participated in any discussions!
> 
> <img alt="image" width="1547" src="https://private-user-images.githubusercontent.com/17853509/403080596-28de955a-08f3-414f-a1e4-edac138493d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg5MDU5NDAsIm5iZiI6MTczODkwNTY0MCwicGF0aCI6Ii8xNzg1MzUwOS80MDMwODA1OTYtMjhkZTk1NWEtMDhmMy00MTRmLWExZTQtZWRhYzEzODQ5M2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA3VDA1MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NjE3ZGEzNDQ3NzI5OTgzM2Q3NjQ3OWMwNmVhMGQyNmE4NGZmN2Y3OTQ0MmQ3YWMzN2RiOThlZWFlMWIxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b4xCHT0CShY1QNsAWH_YVXOEVOFFnvIgU__wkgjBtfw">

**Comment by daviddinhgcp** [comment]
I know we've made a lot of progress towards this solution and I don't want to hold this process up or backtrack any decisions.  However, we don't necessarily agree with the proposed solution of adding a prefix to tags/labels.  If possible, maybe we can delay this solution to the next release in order to allow ample time to develop a more effective solution for our customers and CSPs.  Happy to discuss this on our next TF1 call.

**Comment by ljadvey** [comment]
@daviddinhgcp This has been discussed at length in TF1 and outside of TF1; please see slack poll at https://finopsfoundation.slack.com/archives/C07DHK9704T/p1733181295831449 also see the thread attached to it.  This may be a point of "agree to disagree" and "disagree and commit".

**Comment by cnharris10** [comment]
@daviddinhgcp To Larry's point, here is the consolidated results across polls in the FinOps and FOCUS slack channels showing support for the presented solution.

<img width="1853" alt="Image" src="https://github.com/user-attachments/assets/e973c872-bede-42f8-b9f2-b09af688ac83" />

**Comment by daviddinhgcp** [comment]
Attached is a proposal and detailed explanation to keep tags and labels as separate columns.  

[\[Work_Item\] (BUG) Ensure all user-defined Tags are encapsulated within the Tags column #540.pdf](https://github.com/user-attachments/files/18803529/Work_Item.BUG.Ensure.all.user-defined.Tags.are.encapsulated.within.the.Tags.column.540.pdf)

**Comment by shawnalpay** [comment]
@daviddinhgcp I appreciate the amount of detail you put into this document!  

My main concern in the framing is this: it presumes that the `Tags` column does not yet exist -- but it has been in the spec since FOCUS 1.0 Preview, which was released in late 2023.

For example, consider this section:

> Loss of Granularity
>  * Combining labels and tags into a single column would eliminate the ability to easily differentiate between metadata intended for cost analysis and those used for policy enforcement.

This topic is not greenfield, and so any such concerns were realized a few releases ago; this framing would have been appropriate in the fall of 2023 when the column was initially being authored (see [here](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/227) for the initial PR).  Both the working group and the steering committee approved this addition, and any member had the opportunity to object to its inclusion. **I would encourage you to revise the proposal to advocate for a change to an _existing_ column rather than an alternative to a _new_ one.**

So, if we consider the following section:

> Impact on Existing Reporting
> * Existing reports and dashboards that rely on separate label columns would need to be redesigned.
> * This could lead to disruptions in cost monitoring and reporting workflows.

Pursuit of the proposal as authored would have *more* of an impact on existing FOCUS adoption/reporting, and potentially breaking changes require significant consideration.

I certainly believe that consideration of your proposal has merit.  Therefore, I invite you to create a new issue in the backlog to capture this proposal as a new Work Item for consideration in a future release.  You would also be within your rights to author a pull request that replaces the existing `Tags` column with a new set of columns (it was not immediately clear to me in the proposal precisely what number and naming of columns you would prefer).  

But, because this would be a significant change to a section of the spec that has been in place for multiple releases, I am doubtful that we have the time to consider this change in 1.2.  **In the meantime, I would encourage you to consider whether approval of the bugfix as proposed in PR #691 is preferable to no action.**

Let's discuss further in TF1 this coming Tuesday, and let me know your thoughts in the meantime.

**Comment by cnharris10** [comment]
Thanks @daviddinhgcp for providing additional insight into how user-defined and provider-defined tags are used in GCP and other CSPs. I've read your document a few times now to ensure I'm not missing anything, and here are my (unordered) conclusions:

1. Nothing presented in the document presented indicates that any provider (CSP, SaaS, etc.) cannot follow the `Tags` specification in the v1.0-preview release nor the proposed #691 and achieve 100% data accuracy.  The arguments presented certainly indicate that you would like to offer a different route for presenting this data, and as Shawn indicated above, I would also urge you to present an alternate approach as a work item.

2. The document provided ignores some of the points that currently exist the `Tags` spec since its introduction or presented in the #691 proposal.  Examples include:

- **Example 1** - In this line, `When tag inheritance is enabled, this can lead to situations where billing data contains multiple values for the same tag key, depending on the inheritance hierarchy. This can create confusion during analysis.` ... The normative text since v1.0-preview states, `The Tags column MUST only contain finalized tags.` and this depends on the provider's heuristic for this finalization.  Additionally, the screenshot below from the v1.0-preview spec details an exact example in this case.

<img width="457" alt="Image" src="https://github.com/user-attachments/assets/a4e142ac-247f-46b6-9dc1-6bcab2d054d7" />

- **Example 2** - In this line, `It's possible to use the same tag key for both a resource tag and a billing tag. For example, you might have a resource tag "CostCenter" and a billing tag also named "CostCenter."` ... This is solved in the proposed #691 proposal where either a resource tag (user-defined scheme A) or a billing tag (user-defined scheme B) must have a prefix provided to prevent such a clobbering situation.  I would urge you to familiarize yourself with the #691 proposal and push back if you still believe the proposal does not prevent this issue.

3. The document provided presents arguments highlighting its benefits but fails to consider additional, possible solutions. 
 During this defining process in 2023, a series of avenues were considered by CSP/SaaS/IT/FinOps providers and practitioners and through much discussion, the general agreement landed on the column specification as it is today.  These were some of the additional avenues that were consider but ultimately rejected: 
- Separate columns for all user/provider tags with scalar values
- Separate column for all user-defined tags and a separate column for provider-defined tags

Additionally the group ultimately settled on the current definition due to some of the arguments below:

- **Discoverability** - Combining all user-defined/provided-defined tags into a single column is a scalable solution as FOCUS expands past CSP's and into other SaaS and IT sources.  It allows practitioners to expect that all user/provided-defined tags live in one column.  
- **Flexibility** Given that this is big data and complex, a single-column approach does not limit customers from exploding into multiple columns if they wish, and they can do so without fear of loss of tag fidelity.
- **Searchability** A single column map structure provides a pinpointed, O(1) lookup for practitioners searching for specific tags, and O(N) for discovery of tags.

--

As Shawn said above, there is merit to some of your proposal, and I urge you to continue developing it as a Work Item to further unpack it.  Additionally or alternatively, I also urge you to consider the current #691 and even propose a new option that relates to its objective.

However, given that the document does not attempt address the issue at hand, I agree with Shawn that this is a disjoint effort that should follow the standard work item process for consideration for a later revision.

**Comment by rileyjenk** [comment]
I agree with what @cnharris10 and @shawnalpay have commented above.  In reading the document this seems to be from the perspective that that there isn't already an established tag column, when in fact, there has been since v1.0 preview. Much of the work going into the previous effort to bring the tags column into the spec involved debate on the topics you highlight in your document. I would highlight a few thoughts:
- The spec does not prevent a provider from presenting any of their tag/categorization features as separate custom columns 
- Due to the dynamic nature of tags or other metadata features, keys/attributes will be highly customized and differ across providers. It was desirous that though we wouldn't be able to centralize the "what" we could centralize the "where" as it pertains to this type of data. 
- The  https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/691 is being worked on to address some deficiencies with the current spec and I believe addresses multiple of your concerns.

I believe that this issue should be revisited once the work item associated to https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/691 is resolved that the issue be reviewed and, if deemed necessary, a work item be drafted for a future version.

**Comment by shawnalpay** [comment]
This Work Item is now complete.  However, Google Cloud has created #788 to propose replacement of the `Tags` column with a series of new columns that split out the various allocation mechanisms (e.g. tags, labels, etc).  We will discuss this further during 1.3 scope development.  Thanks to everyone who helped get this across the finish line!
