### ISSUE TITLE
[DISCUSSION]: List of issues to be discussed and potentially addressed as part of the FOCUS 1.1 Consistency Review

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#542]
#### Corrections (TF-1) Irena

Review and align how we specify Corrections across the specification.
In the case of CommitmentDiscountQuantity, we specified the following:

> … CommitmentDiscountQuantity MAY be negative if ChargeClass is "Correction"….

Meanwhile, for other columns (e.g., costs, quantities, units), we allowed null values for Corrections. For instance:

> … It MUST NOT be null when ChargeClass is not "Correction"…

#### Negative and Zero Values in Metric Columns (TF-1) Irena

While we were explicit in CommitmentDiscountQuantity about expecting positive values and allowing negative values for Corrections, we didn’t explicitly address negative values in other metric columns. (We assumed it was understood that quantities and costs can only be negative in the case of Correction charges and must be non-negative for non-Correction charges.) 
Briefly discuss whether this should be applied consistently across the specification.

#### Double Counting (TF-1) Alex

Due to Commitment Discounts, the following columns are prone to double counting:

- PricingQuantity
- ListCost
- ContractedCost
- CommitmentDiscountQuantity

TODOs:

- We didn’t explicitly address this issue in PricingQuantity. 
- Additionally, I suggest a quick review and alignment of the guidelines across all of these columns.

#### Commitment Discount Flexibility or ~Commitment Flexibility~  (TF-1). Chris

We’ve used both terms, so we need to choose one.

Additionally, I suggest we verify the following statement:

> A given value of SkuPriceId MUST be associated with one and only oneSkuId, except in cases of
commitment discount flexibility.

#### Formatting (Editorial Guidelines)   (TF-X) Udam, Riley

Align formatting with the established editorial guidelines. 

#### Changelog  (Maintainers | Members, TF-2) Michael

- Confirm that we have reached consensus on introducing breaking changes in FOCUS 1.1.
- Discuss whether any adjustments to the current Changelog structure are needed (e.g., how we plan to emphasize breaking changes, if we agree to introduce them).

- Compare relevant working_draft Git commits, identify, categorize, and describe the differences. Some of the expected changes are :
  - Breaking Changes:
    - Mostly bug fixes
    - Commitment discount-related columns strictly limited to standard commitment discounts
    - Update to Commitment handling attributes
  - Editorial Changes:
    - Normative paragraphs
    - Etc.
  - Metadata Updates
  - New Columns
  - New Glossary Terms
  - Etc.

### Commitment Discount Appendix (TF-1)  Chris
 - Old language

**Comment by jpradocueva** [comment]
### Action Items from Maintainers' call on Sep 23:
- [ ] [TF-1-[#542](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/542)] Corrections, assigned to Irena, @ijurica 
- [ ] [TF-1-[#542](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/542)]] Negative and Zero Values in Metric Columns assigned to Irena, @ijurica 
- [ ] [TF-1-[#542](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/542)]] Double Counting, assigned to Alex, @ahullah 
- [ ] [TF-1-[#542](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/542)]] Commitment Discount Flexibility or Commitment Flexibility, assigned to Chris, @cnharris10 
- [ ] [TF-X-[#542](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/542)]] Formatting (Editorial Guidelines), assigned to Udam, @udam-f2 , and Riley, @rileyjenk 
- [ ] [TF-2-[#542](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/542)]] Changelog (Maintainers | Members), assigned to Michael, @flanakin 
- [ ] [TF-1-[#542](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/542)]] Commitment Discount Appendix, assigned to Chris, @cnharris10 
- [ ] [TF-1-[#542](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/542)]] Metadata, assigned to Riley @rileyjenk , and Udam, @udam-f2

**Comment by ijurica** [comment]
It seems that this issue has been addressed (all action points have been successfully resolved) and can be closed.

**Comment by shawnalpay** [comment]
Excellent.  Closing.
