### ISSUE TITLE
[DISCUSSION]: FOCUS Backlog for 1.2 Forward 

### ISSUE THREAD

**Issue by jpradocueva** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#605]
### Document
* Spreadsheet: [FOCUS Backlog for 1.2 Forward](https://docs.google.com/spreadsheets/d/1Pn7WDfQ-VMk5qHYqFN7KD6IdGjbTdDLi2J98sadkvAU/edit?gid=580467466#gid=580467466)

### Proposed Approach

This document suggest to introduce a list of labels to qualify the different items (Issues and PRs) discussed by the group.

### Context

This topic was discussed during the Maintainers' call on Oct 14. It was agreed to assign an Issue # to easily track how the proposal is evolving.

**Comment by jpradocueva** [comment]
### Action Items assigned during the Maintainers' call on Oct 14:
- [ ] [Maintainers-[#605](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/605)] Shawn, @shawnalpay: will clean up backlog tagging and prepare issues to be reviewed for the next 1.2 scope discussions in Task Force meetings.

**Comment by jpradocueva** [comment]
### Action Items from Maintainers' call on Oct 21:
- [ ] [[#605](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/605)] Shawn @shawnalpay to continue backlog curation.
- [ ] [[#611](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/611)] Stakeholders to provide feedback on prioritized items.

**Comment by shawnalpay** [comment]
@jpradocueva Do you feel we can close this issue?  If not, what do we need to do in order to consider closing it?

**Comment by jpradocueva** [comment]
@shawnalpay, feel free to close it if you think it is no longer needed. I created it to easily track issues from meeting agendas.

**Comment by shawnalpay** [comment]
Legacy issue that was completed.  Closing.
