### ISSUE TITLE
Tracking issue for 1.2 Work Items

### ISSUE THREAD

**Issue by shawnalpay** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#611]
The scope for FOCUS 1.2 was approved by the Steering Committee on November 21, 2024.  The list of `Work Items` (both approved and considered) can be found below.  Alternatively, the list of approved `Work Items` can be found under the `1.2` label [here](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/labels/1.2).

## Work Items approved for 1.2
The `Work Items` included in 1.2 can be grouped into the following themes:

- Initial Software as a Service (SaaS) Support
  - Addition of columns to support **SaaS-centric concepts** and billing models
- Continued expansion of Cloud Service Provider concepts
  - Addition of **Invoice ID** to support invoice reconciliation use cases
  - Addition of **SKU properties** that are prominent / common across providers
  - Addition of **Commitment Discount Unit Price and Cost**
- Fixes and clarifications
  - **Revisions of existing specification content** to increase consistency and reduce ambiguity

| Theme     | Issue                                                                                                                                                           |
| --------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| SaaS      | [#616](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/616) Document and add support for SaaS concepts                                     |
| Revisions | [#314](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/314) Clarify definition for SKU ID                                                  |
| Revisions | [#317](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/317) Add columns that describe provider entities in Billing Account and Sub Account |
| Revisions | [#540](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/540) Address bug that allows overlapping user-defined Tag structures                |
| Revisions | [#556](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/556) Augment support for correction handling                                        |
| Revisions | [#557](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/557) Refine normative requirements for all existing spec content                    |
| Revisions | [#617](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/617) Revise glossary definition for FOCUS dataset to include provider columns       |
| Revisions | [#636](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/636) Clarify guidance around Refunds                                                |
| Revisions | [#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643) Formally define backward compatibility                                         |
| Revisions | [#647](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/647) Prevent double-counting of Commitment Discounts                                |
| CSP       | [#534](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/534) Add Commitment Discount Price and Cost                               |
| CSP       | [#615](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/615) Add Invoice ID                                                                 |
| CSP       | [#619](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/619) Add SKU properties (e.g. term, tier, SKU region)                               |

Additionally, the following `Work Item` shall be further explored in partnership with the Sustainability Special Interest Group (SIG), with the group's recommendations released alongside the 1.2 spec for inclusion in a future release:

#637 Add **carbon footprint** data for **sustainability** use cases

## Work Items added to 1.2
Here is a list of Work Items that have been brought into scope for 1.2 as either decomposition of existing work items or as supporting content around the specification itself:

- #666 
- #678

## Work Items considered for 1.2

For posterity, here is the full list of `Work Items` that were considered for 1.2.  These `Work Items` sorted by 👍 reactions can be found [here](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3A%22work+item%22).

#72 Facilitate **provider-performed shared cost allocation**
#314 Clarify definition for **SKU ID**
#317 Add columns that describe **provider entities in Billing Account and Sub Account**
#406 Facilitate Coverage % KPI by tracking **commitment-eligible cost**
#510 Add **Service Model** (e.g IaaS, PaaS, SaaS)
#520 Add support for **experimental datapoints**
#534 Expose **Commitment Discount price and cost** to facilitate forecasting and ESR KPI
#540 Address bug that allows **overlapping user-defined Tag structures**
#556 Augment support for **correction handling**
#557 Refine **normative requirements** for all existing spec content
#608 Add **SKU categories / hierarchy / taxonomy**
#610 Determine principles for **primitives vs derivatives**
#613 Guidance for incorporation of **on-premises cost and usage**
#614 Add metadata to describe **data recency**
#615 Add **Invoice ID**
#616 Document and add support for **SaaS concepts**
#617 Revise **glossary definition for FOCUS dataset** to include provider columns
#618 Add **Account / Resource hierarchy attributes**
#619 Add **SKU properties** (e.g. term, tier, SKU region)
#634 Add appendix for **commitment size flexibility**
#636 Clarify guidance around **Refunds**
#637 Add **carbon footprint** data for **sustainability** use cases
#643 Formally define **backward compatibility**
#647 Prevent **double-counting** of commitment discounts

**Comment by jpradocueva** [comment]
### Action Items TF-1 call on Oct 22:
- [ ] [[#611](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/611)] Team members: Review assigned items and add practical examples.
- [ ] [[#613](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/613)] Alex @ahullah : Prepare use cases for non-cloud asset guidance and follow up with Karl for insights into prior work on on-prem perspectives.

**Comment by jpradocueva** [comment]
Action Items from the Members' call on November 21:
- [ ] [[#611](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/611)] Shawn, @shawnalpay : Finalize and present the 1.2 work item proposal to the steering committee.

**Comment by shawnalpay** [comment]
1.2 was completed!  Closing this issue.
