### ISSUE TITLE
[FEEDBACK]: Ability to Custom Add FOCUS 'columns'

### ISSUE THREAD

**Issue by dklambert88** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#622]
### Proposed Change

Ability to custom add focus columns for cloud providers to incorporate across all billing files for a specific company.

### What use cases, FinOps or others, can't be performed with the current specification without this change?

There will always be some standardization/overlay done and mappings on the back end if there isnt customization allowed across the clouds.

### Which FinOps personas perform this use case?

Billing Management Team

### For which providers do you perform this use case for?

AWS, Azure, GCP, IBM Cloud, OracleCloud

### Criticality Scale

3: Important for adoption in the next 6-12 months

### Key Metrics and KPIs

Customized business mappings and columns in bill that apply to a specific company.

### Context / Supporting information

TBD

### Data Submission for Discussion

TBD

**Comment by shawnalpay** [comment]
Hi @dklambert88 -- thanks for adding an issue to the backlog!  

The project team discussed this issue today.  The FOCUS spec already allows providers to add their own custom columns to the dataset; for example, the Microsoft export provides `x_ResourceGroup`, which is an attribute that groups Resources, and it has not (yet) been added as a FOCUS column.

That said, we recognize that we need to add some guidance around this topic, and so we have defined `Work Item` https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/617 to revise the glossary to make this more clear.  

I believe this issue can therefore be closed in lieu of that `Work Item`; let me know if you agree / disagree.  I will close this issue next week if I don't hear back by then.  Thanks!

**Comment by jpradocueva** [comment]
### Action Items from the TF-1 call on November 5:
- [ ] [[#622](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/622)] Documentation Team: Update FOCUS documentation to clarify the custom column functionality, specifically the use of the “x-” prefix, and provide examples of possible use cases.
- [ ] [[#622](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/622)] Alex @ahullah : Investigate whether additional metadata attributes could be introduced in future releases to help manage and standardize custom columns across different organizations.
- [ ] [[#622](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/622)] Shawn @shawnalpay : Agreed to reply to the submitter of Issue #622. He planned to confirm that the existing functionality allows for custom columns using the "x-" prefix and proposed to close the issue after providing this information. Additionally, he would mention the planned documentation updates to clarify this capability.

**Comment by shawnalpay** [comment]
Closing, per my previous note.  Please feel free to reopen if you have further context to provide!
