### ISSUE TITLE
[WI] Cloud Sustainability

### ISSUE THREAD

**Issue by bndshrm** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#637]
## 1. **Problem Statement** *
> Describe the problem, issue, use case, or opportunity that this work item addresses.
> Include practitioner quotes illustrating real examples a) of questions being asked by practitioners and b) value unlocked by answering these questions, if available.
> - What is the problem?: Explain the context and why it needs resolution.
> - Impact: Describe how the problem affects users, systems, or the project.

The FOCUS Spec should
•	We need to be able to understand the carbon equivalent (CO2e) of our cloud usage down to the resource level
•	Normalize the carbon equivalent data from different sources (CSPs, SaaS vendors and regulators)

### Use cases:
❗ See [How to craft a use case](https://docs.google.com/document/d/1oMV78K7cGmQ5cjcAv_aZBe-sQzV9zatvJVTEsE7aL7M/edit?tab=t.0)
•	Visibility into the carbon footprints
•	Allow decision making including cost and carbon equivalent
•	Helps make decision on the power source (renewables, nuclear)

## 2. **Objective** *
> State the objective of this work item. What outcome is expected?
> * Success Criteria: Define how success will be measured (e.g. metrics and KPIs).

Promote, advance, and socialize Cloud Computing Sustainability Best Practices to reduce the environmental impact of public cloud. Forge partnerships with ESG leaders, practitioners, and vendors, establishing unified operational standards and processes that advance Cloud Sustainability, seamlessly integrating it into broader enterprise Sustainability practices.

## 3. **Supporting Documentation** *
> Include links to supporting documents such as:
> - Data Examples: [Link to data or relevant files; DO NOT share proprietary information]
> - Related Use Cases or Discussion Documents: [Link to discussion]
> - PRs or Other References: [Link to relevant references]

KPIs are listed in below document
https://docs.google.com/document/d/12Qkw1ZXxskNKTwzi5eQxAFn-9o1uuEFUo8Zu243dYHg/edit?tab=t.0

## 4. **Proposed Solution / Approach**
> Outline any proposed solutions, approaches, or potential paths forward. Do not submit detailed solutions; please keep suggestions high-level.
> 
> - Initial Ideas: Describe potential solution paths, tools, or technologies.
> - Considerations: Include any constraints, dependencies, or risks.
> - Feasibility: Include any information that helps quantify feasibility, such as perceived level of effort to augment the spec, or existing fields in current data generator exports.
> - Benchmarks: Are there established best practices for solving this problem available to practitioners today (e.g. mappings from existing CSP exports that are widely used)?

n/a

## 5. **Epic or Theme Association**
> This section will be completed by the Maintainers.
>
> - Epic: [Epic Name]
> - Theme: [Theme Name, if applicable]

Sustainability

## 6. **Stakeholders** *
> List the main stakeholders for this issue.
> 
> - Primary Stakeholder: [Name/Role]
> - Other Involved Parties: [Names/Roles]

Bindu Sharma (Teradata)

**Comment by jpradocueva** [comment]
### Action Items from the Members' call on November 7:
- [ ] [[#637](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/637)] Shawn: Draft a proposal work item for an experimental sustainability field in FOCUS, including suggested metrics and guidelines for CSPs to provide optional carbon data.
- [ ] [[#637](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/637)] All Members: Review and provide input on the experimental sustainability field proposal, focusing on practical applications and data consistency across providers.

**Comment by shawnalpay** [comment]
@bndshrm Thank you for authoring this issue!  I have converted it into the `Work Item` format in order to consider it formally for a future release.  All the guidance you shared in your original post should still be there; feel free to edit and add more if you see fit.

**Comment by jpradocueva** [comment]
### Action Items from TF-1 call on November 19:
- [ ] [[#637](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/637)] Shawn @shawnalpay : Propose a research group to the steering committee for approval.
- [ ] [[#637](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/637)] Bindu Sharma: Identify and recommend 10 subject matter experts for the research group.
- [ ] [[#637](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/637)] Mark @marc-perreaut : Share links to current provider documentation on carbon data reporting.
- [ ] [[#637](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/637)] All Members: Review sustainability use cases and challenges to prepare for collaboration with the research group.

**Comment by Kbjng** [comment]
@shawnalpay do we a research group yet? Thanks

**Comment by shawnalpay** [comment]
@Kbjng Not yet!  I shall be proposing the creation of a Research Group to the FOCUS Steering Committee this week, and pending that outcome, we will decide on next steps.  I'll circle back!

**Comment by Kbjng** [comment]
@shawnalpay That’s awesome. Thanks for the good work.

**Comment by robmartin33** [comment]
Summary of Maintainers Call on Feb 10. 

Review of the [[Deliverable document](https://docs.google.com/document/d/1UTyW0ATNxxBRImz0fIHBwJJcJ9DgT39E2mluJNoRm-E/edit?tab=t.0#heading=h.6y0n8dvtgjc5)

Several Items were added in that meeting. 
Group will not meet Feb 17. 
Group will meet Feb 24, likely for last time.

**Comment by robmartin33** [comment]
A working group convened of members of the Sustainability Special Interest Group and others interested in FOCUS has been met between 12/2/24 and 3/24/25. That working group developed two outputs
- [Sustainability Use Cases - Sustainability Data in the FOCUS dataset](https://docs.google.com/document/d/1UTyW0ATNxxBRImz0fIHBwJJcJ9DgT39E2mluJNoRm-E/edit?usp=sharing)
- [Sustainability FOCUS Sheet - listing sustainability data descriptions and equations](https://docs.google.com/spreadsheets/d/176WEQLwPBiofveKpdQ-ZJ2Vm-trBtgKxrwuNTWVlJv8/edit?usp=sharing)

These documents serve to capture the requested sustainability information that would be requested by FinOps practitioners using FOCUS datasets as inputs and interested in supporting their documented use cases to use sustainability data. 

This detail is being provided to support this feature request work item in prioritizing for future FOCUS releases. 
Thanks to this working group which included representatives of over a dozen FinOps practitioners who are listed in the documents.

**Comment by marc-perreaut** [comment]
While 1 USD is the same for every provider, 1 CO2eq g can be different. Same applies for Energy and other sustainability metrics. This depends on the calculation method. For a single provider, there could be different calculation methods. It could be interesting to standardize/inventorize the different calculation methods, (some might be specific by provider), so as to attach sustainability metrics columns to them.

**Comment by Matt-Cowsert** [comment]
The scope of this request is captured in feature request #972. Closing this WI as we've moved to tracking scope and development of requests using feature requests.
