### ISSUE TITLE
Practitioner defined cost allocation

### ISSUE THREAD

**Issue by ahullah** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#638]
### Problem Statement

For more advanced cost allocation, use cases. Provider driven allocations may be insufficient or may differ across provider. For larger enterprises where standardisation is important, it is important to allow practitioners to control the allocation methodology and define their own as necessary. Supported by appropriate allocation, metrics and strategies.

Consume usage metrics and cost data for practitioner to perform cost allocations
Often uses alternative data sources outside of cost and usage
Prometheus for usage metrics
Spreadsheet for split percentages

### Objective

To provide a guideline in the form of supporting content for all potential data sources, potentially a reference data architecture to achieve the desired practitioner driven allocation strategies in a consistent way. Including third-party logging systems such as  Prometheus or other metric sources to support effective cost allocation.

### Supporting Documentation

Content follow the expect to support a variety of allocation processes consistent with other methodologies in this space. E.g.. technology business management

### Proposed Solution / Approach

Supporting content will explore other common metric data sources, how they are related to focus and reference data architecture or performing simple to advanced cost collocation across multiple providers and services

### Epic or Theme Association

Provide the rational for the Epic or Theme.

### Stakeholders

Provide names and roles of key stakeholders.

**Comment by jpradocueva** [comment]
### Note from Maintainers' call on November 4:
**Context:** This subtopic is related to #72 but focuses on providing practitioners with guidance on implementing shared cost allocation independently of provider-generated data. This guidance would support practitioners in custom setups where standardized provider allocations aren’t sufficient.
**Level of Effort Required:** Very High — This item requires a comprehensive approach, as practitioners will need detailed instructions for calculating shared costs in various cloud environments.

**Comment by shawnalpay** [comment]
@ahullah, per our conversation in TF1 today, please add:

- Specific artifacts you would expect this exercise to generate, and the content within.
- Verbiage around how this is guidance on how to execute on shared cost allocations with _FOCUS_ data specifically.

From there, we can hand it off over to @robmartin33 for consideration in a Working Group.  To that end, and per today's discussion, we will pull this `Work Item` from 1.2 consideration, as the output generated by the Working Group would inform what we might add to the FOCUS spec itself.  At that time, we would revisit this `Work Item`.

**Comment by jpradocueva** [comment]
### Action Items from the TF-1 call on November 5:
- [ ] [[#638](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/368)] Alex @ahullah : Augment #638 to clarify artifact expectations, focusing on FOCUS-specific data and outputs for practitioner allocations.
- [ ] [[#638](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/638)] Alex @ahullah : Document specific practitioner allocation methods in #638, focusing on examples using Prometheus data and shared resource allocation.
- [ ] [[#638](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/638)] Team: Review additional sources that could aid in custom allocation strategies and propose a list of recommended tools and datasets for future FOCUS experimental columns.

**Comment by jpradocueva** [comment]
### Comments from the Members' call on November 7:
[#638](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/638): This item was excluded from the v1.2 scope, as it involves broader practitioner actions with data that goes beyond current FOCUS specifications. The group agreed to pass this issue to a separate working group to explore related data models and allocation strategies.

**Comment by RenarsBD** [comment]
Consistent Tags and metadata across all Business Units is critical to provide proper reporting, transparency and allocation for all involved personas. Aim to use minimal amount of tags to achieve most efficient resource labeling.

**Business Unit** tag is name of self sufficient Business Unit.

**Financial Entity** tag is used to represent Financial Entity within Business Unit. Department that is paying the bill.

**Cost Center** tag is used to group or assign costs in the following ways:

Collection of smaller applications: combine multiple small applications into a single cost bucket that is shared among various financial entities.

Product with internal cost center: Consolidate one or more smaller applications under a single internal cost center.

**Financial Entity:** Allocate applications exclusively used in specific markets directly to the corresponding financial entity.

**Application Name** tag is a concise and meaningful label for an application, product, or solution. It helps identify and differentiate various resources within cloud environment.

**Application Owner** tag identifies the person responsible for an application, product, or solution. This individual has the authority to oversee and approve changes, downtimes and resource decommissioning.

**Environment** tag represents a label of resources to indicate the type of environment they belong to, such as Development, Testing, or Production. This helps you organize and manage resources more effectively, like powering off Testing resources on weekends.

Core Cost Allocation Concepts
Organizations have varying needs in how they allocate and share costs out. The most common allocation strategies include: **Even Split**, **Fixed Weighting**, **Proportional (By Direct Charges)** based allocations.

The various types of costs incurred are:

Direct cost: Costs derived through raw data ingestion, synthetic tagging, or business mapping decoration

Shared cost: Costs received through cost sharing rules from source dimensional values

Total cost: Combined value of direct and shared costs for any dimensional value

Allocation Strategies
**Even Split** –Defines a spread of direct costs (either a single dimensional bucket’s direct charge or multiple dimensional bucket’s direct charges) across a set of dimensional buckets at equal value.

**Fixed Weighting** - Uses fixed weights as a percentage, a breakout of direct costs (either a single dimensional bucket’s direct charge or multiple dimensional bucket’s direct charges) based off a user-defined weighting.

**Proportional - Direct Charges** - Uses the direct cost as the weighting allowing organizations to dynamically weigh the allocation based off the source destination’s direct charges. Proportional weighing will take into account the source buckets direct charges when it calculates the assignment ratio for the given allocation.

Based on 6 mandatory tags mentioned above different many cost buckets can be created\filtered aka synthetic tag.

Cost Sharing helps organizations share out line items to help properly account for spend and help facilitate accurate and defensible showback and chargeback exercises. Cost sharing is built builds on the [Business Dimensions] or synthetic tag functionality to provide even further granularity on how direct costs can be shared out.

Sharing of costs is the act of taking a bucket of spend (e.g. a dimensional value's direct charges) and sharing that value across a list of destination dimensional values, so those destinations are burdened by the source's direct cost. A simple way to think about this is every dimensional value has a direct cost. This cost has been derived through a combination of raw data ingestion of said resource cost, synthetic tagging of said resource cost, and/or decoration of said resource cost through conditional logic done in our business mappings feature.

Since each dimensional value has a direct cost, when they are on the receiving end of cost sharing (meaning, they have some sort of cost that has previously been shared with them through cost sharing feature) the also consume a shared cost. This means, for any post allocated dimensional value, it has a direct cost, shared cost, and a total cost (direct+shared).

Hope this is helpful.

**Comment by Matt-Cowsert** [comment]
The scope of this request is captured in #973. Closing this WI as it's no longer being using to track scope and development. WI is also captured within the supporting documentation of the related FR.
