### ISSUE TITLE
[DISCUSSION]: Granularity of SaaS data passing through CSP exports

### ISSUE THREAD

**Issue by shawnalpay** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#640]
### Description

The practitioner needs visibility of granular usage data for a data generator in order to unlock a whole host of use cases: cost allocation, charge back, recommendations, rightsizing, etc.  We have recently heard from multiple practitioners that SaaS cost and usage data when provided through the marketplace of a cloud service provider is often very highly aggregated.  Here is a quote from one practitioner:

> In one of our use cases, we are utilizing Databricks on GCP via the marketplace, and we are facing challenges in accurately determining the cost breakdown for each component used by both GCP and Databricks in order to calculate the total cost of ownership. We are actively seeking a solution to address this issue and are eager to contribute towards finding a resolution.

While that particular example is potentially an issue between the SaaS provider and the CSP, and while it would be ideal for the practitioner to consume more granular data from the SaaS provider, the CSP generator is perfectly conformant with the FOCUS spec as currently authored.

### Proposed Approach

Augment the FOCUS specification to either suggest or require usage data to be provided at a certain granularity that would unlock a certain quality of data to facilitate various practitioner use cases.  The various suggestions or requirements are TBD and would require further analysis and discussion.

### GitHub Issue or Reference

#616

**Comment by jpradocueva** [comment]
### Action Items from TF-2 call on Nov 6:
- [ ] [[#640](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/640)] Andrew @aqu-erp : Investigate current data granularity capabilities across major CSPs and SaaS providers to determine potential guidelines for the FOCUS specification.
- [ ] [[#640](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/640)] Shawn @shawnalpay : Draft a proposal outlining possible FOCUS guidelines for SaaS data granularity for discussion in an upcoming meeting.

**Comment by jpradocueva** [comment]
### Action Items from the Members' call on November 7:
- [ ] [[#640](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/640)] Irena @ijurica : Draft a preliminary guideline for the recommended granularity of SaaS data in CSP exports, covering key data points such as itemized services, tax details, and purchase records.
- [ ] [[#640](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/640)] All Members: Review and provide feedback on the preliminary guideline and identify any additional data elements or considerations that would be beneficial for SaaS granularity in CSP data exports.

**Comment by shawnalpay** [comment]
@Matt-Cowsert Please steward a Feature Request for this, either net-new, or folded underneath an existing "SaaS through Marketplace" Feature.  @rileyjenk would likely have more context for this.

**Comment by Matt-Cowsert** [comment]
moving over org support to #1063
