### ISSUE TITLE
[DISCUSSION]: Relationship of CSP vs SaaS with origination of cost data elements (i.e. Provider, Publisher, and Invoice Issuer)

### ISSUE THREAD

**Issue by shawnalpay** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#641]
### Description

Some SaaS providers like Snowflake sit atop cloud service providers (CSPs) and are agnostic in their deployment and management.  For example, Snowflake can sit stop either AWS, Azure, or GCP, depending on the client's requirements.  For more information, see Snowflake's documentation [here](https://docs.snowflake.com/en/user-guide/intro-cloud-platforms).

The FOCUS specification's current definition of `Provider`, `Publisher`, and `Invoice Issuer` for SaaS data, according to the [origination of cost data appendix](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/main/specification/appendix/origination_of_cost_data.md), reads as follows:

| #   | Scenario                                                                                                                                      | Provider                 | Publisher                                                                                                              | Invoice Issuer                                              |
|:----|:----------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------|:-----------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------|
4.1 | Purchasing SaaS software directly from provider                                                                                               | SaaS provider            | SaaS provider                                                                                                          | SaaS provider                                              |
| 4.2 | Purchasing SaaS software that additionally runs on your cloud resources (in addition to 4.1)                                                 | Cloud service provider   | Cloud service provider                                                                                                 | Cloud service provider                                     |

Definition of those fields:
- Provider: The entity that made the resources or services available for purchase.
- Publisher: The entity that produced the resources or services that were purchased.
- Invoice Issuer: The entity responsible for invoicing for the resources or services consumed.

When considering the Snowflake example, a FinOps vendor representative wrote as follows (emphasis mine):

> Based on the definition and 4.1, I think the values would just be "Snowflake", "Snowflake", and "Snowflake".
> 
> We would still sort of have the underlying cloud provider in the "Region" as its "Azure West US 2" or similar.  But you lose that hierarchy a bit for an organization using Snowflake in multiple clouds and regions that might want to see that rollup.  The "**Underlying cloud provider**" which is a somewhat unique concept for Snowflake.
> 
> I have an opinion that **we shouldn't lose that AWS/Azure/GCP underlying cloud for Snowflake**.  While it doesn't match the definition, "Provider" seems the most logical. 

### Proposed Approach

Provide insight to the "underlying CSP" leveraged by SaaS providers such as Snowflake.  Whether this would be a change to an existing column or an addition of another column in the specification is TBD, pending further discussion.

### GitHub Issue or Reference

#616

**Comment by jpradocueva** [comment]
### Action Items from the TF-2 call on November 6:
- [ ] [[#641](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/641)] Shawn @shawnalpay : Draft a proposed addition to the FOCUS specification that distinguishes between invoice issuers and data generators, including suggested attribute examples.
- [ ] [[#641](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/641)] Riley @rileyjenk : Gather insights from SaaS providers on their invoicing structures and share findings on potential challenges in differentiating invoice issuers in mixed-provider scenarios.

**Comment by jpradocueva** [comment]
### Action Items from the Members' call on November 7:
- [ ] [[#641](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/641)] Shawn @shawnalpay : Document the optional approach for including CSP details in SaaS cost data, clarifying the contexts where it could be most beneficial.
- [ ] [[#641](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/641)] All Members: Review and provide feedback on any additional complexities or challenges associated with including CSP details in SaaS cost tracking for the next iteration of this discussion.

**Comment by shawnalpay** [comment]
@Matt-Cowsert We need a Feature Request for this, and it will correspond to the Work Item @rileyjenk created as #985.  We can then close this issue as a duplicate.
