### ISSUE TITLE
[Work_Item] Define change management principles to determine backwards compatibility

### ISSUE THREAD

**Issue by AWS-ZachErdman** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#643]
### Problem Statement

FinOps practitioners who adopt FOCUS will need to upgrade to new versions over time as they are released in order to be able to receive the new features provided. However, upgrading to a new version from an old version becomes challenging if, between the new and previous version, there are changes requirement dictating how data must appear in a given column. This would mean the new specification is not "backwards compatible" and this change would be a "breaking change".  

Breaking changes may require practitioners who upgrade FOCUS versions to either (1) update their existing SQL queries that they used to run on the previous version in order to generate the desired results in the new version or (2) modify a FOCUS export such that the data of an existing column in a new export version matches the requirements of the previous version so that they do not need to change their queries.

### Use Case
NA

### Objective

The FOCUS working group recognizes that breaking changes make it more difficult for FinOps practitioners to upgrade to new FOCUS versions and thus, should be avoided when possible. However, breaking changes may be required in certain circumstances when the benefit of the change outweighs the cost it presents to practitioners to adopt.

This work item should result in clear rules for how the FOCUS working group handles breaking changes when formulating new FOCUS versions to make sure that practitioners don't have to deal with breaking changes that don't add tangible value to their FinOps practices. In order to do this, we will define:

1. What is a "breaking change" and "backwards compatibility" according to FOCUS?
2. How do we evaluate the benefit and cost to a practitioner of a breaking change?
3. How can we change our specification development process to ensure we are properly evaluating breaking changes?

### Supporting Documentation

- https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/578

### Proposed Solution / Approach

We will add guidelines in our FOCUS github repo that clearly define what a breaking change is and how they should be evaluated. We may also update some of our issue and work item templates to include references to breaking changes.

### Epic or Theme Association

Epic: [Backwards Compatibility]

### Stakeholders

Primary Stakeholder: Zach Erdman (AWS)

**Comment by jpradocueva** [comment]
### Summary from the Maintainers' call on Nov 25:
 Context:
The aim is to document and formalize principles that ensure backwards compatibility across FOCUS versions, balancing innovation with stability for users.
This WI needs to be defined as soon as possible as the rest of WIs may have a dependency with the finding from this work.
Maintainers Assigned:
Zach, Riley
Task Force Assigned:
Task Force 2 (TF2), which deals with long-term strategy and compatibility.

**Comment by jpradocueva** [comment]
### Action Items from the Members' call on December 5:
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Riley @rileyjenk : Draft a document outlining proposed compatibility tiers and share for feedback.
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Volunteer: Map potential changes to compatibility tiers and identify high-risk scenarios.
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] All members: Review the draft compatibility principles and provide feedback before the next TF meeting.

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on December 9:
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Letian @letian-wang-92 to confirm with Mohit Gupta their ability to lead and participate in backward compatibility discussions.
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Riley @rileyjenk  to share the current notes document with Letian and Mohit for review.
[[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Shawn @shawnalpay to set up a focused meeting with AWS representatives to discuss next steps if necessary.

**Comment by jpradocueva** [comment]
### Action Items from the TF-2 call on December 11:
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Riley @rileyjenk : Refine the change classification framework and propose additional examples for each category.
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] All Members: Review the use case library to determine whether it adequately defines the supported scenarios and identify gaps that may require documentation in the specification.

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on December 16:
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Riley @rileyjenk : Review the use case library to filter out scenarios that are currently supported (by which version) and categorization of change types.
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Maintainers to decide: is the use case library our official source for scenario-based compatibility?

**Comment by jpradocueva** [comment]
### Action Items from the TF-2 call on December 18:
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Shawn @shawnalpay : Provide a consolidated spreadsheet of use cases and queries to ensure all team members work from the same data source.
- [ ] [#643] Shawn @shawnalpay /Irena @ijurica : Define a version-specific list of supported use cases to establish a baseline for compatibility classification.
- [ ] [#643] Beau @beau-nelford-anglepoint : for each use case query, determine whether it is supported by FOCUS 1.0
- [ ] [#643] Beau @beau-nelford-anglepoint :  for each use case query, determine whether it falls into one of the following categories when comparing 1.0 and 1.1:
      1) No change
      2) Degraded / deprecated support
      3) Same support, but modification required
- [ ] [#643] Riley @rileyjenk : Go through 10 “high-importance” columns and do similar classifications as the above from a column perspective alongside the use case perspective

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' meeting on Jan 6:
- [ ] [#643] Dave Hatcher - Categorize all use cases from FOCUS 1.0 and 1.1 into the three compatibility categories.
- [ ] [#643] Riley - Categorize all columns in the specification based on the same compatibility principles.

**Comment by jpradocueva** [comment]
### Action Items from the TF-2 call on Jan 8:
- [ ] [#643] Beau @beau-nelford-anglepoint : create a brief service level pass with a sample set for 1.0, and 1.1 . Check use cases that are unchanged and flag the ones that have changed columns to see if they are no longer supported.

**Comment by jpradocueva** [comment]
### Action Items from Members' call on Jan 9:
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Beau @beau-nelford-anglepoint : create a brief service level pass with a sample set for 1.0, and 1.1 .Check use cases that are unchanged and flag the ones that have changed columns to see if they are no longer supported.
- [ ] [[#643](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/643)] Beau  @beau-nelford-anglepoint - Review all use cases to classify them into No Change, Supported with Change, or No Longer Supported categories.
