### ISSUE TITLE
[WI] Prevent double-counting list/contracted cost for commitment discounts

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#647]
### Problem Statement

When calculating savings, you need to compare the sum of `ListCost` or `ContractedCost` with the sum of `EffectiveCost`. When doing that, commitment discount purchase costs are double counted because both the purchase and usage records have a `ListCost` and `ContractedCost`.

**Use Case**
NA

### Objective

Practitioners have a simple method to calculate savings that doesn't accidentally double-count commitment discount purchase costs.

### Supporting Documentation

This example demonstrates a commitment discount that gets 50% off list price when the organization has an 20% discount on all usage.
ChargeDescription | ChargePeriodStart | ListCost | ContractedCost | BilledCost | EffectiveCost
---|---|---:|---:|---:|---:
Reservation | Jan 1 | $365.00 | $365.00 | $365.00 | $0.00
VM usage | Jan 1 | $2.00 | $1.80 | $0.00 | $1.00
VM usage | Jan 2 | $2.00 | $1.80 | $0.00 | $1.00
VM usage | ... | ... | ... | ... | ...
VM usage | Dec 31 | $2.00 | $1.80 | $0.00 | $1.00
Sum of 365 days | Jan 1-Dec 31 | $1,095.00 | $1,022.00 | $365 | $365

### Proposed Solution / Approach

Some options:
1. Cut: ~Split ListCost and ContractedCost into separate columns for actual and amortized cost.~
2. Add another column that identifies amortizable costs to make them easier to filter out.

One proposal for option 2:

`AmortizationCategory` column with values of:
- **Principal** – Original charge that gets amortized over time (e.g., commitment discount purchases).
- **Amortized Charge** – Rows that are a breakdown of the principal payment (e.g., commitment discount usage).

I avoided the words "purchase" and "usage" here since we could have purchases amortized down to recurring purchases in the future.

### Epic or Theme Association

Savings calculation

**Comment by cnharris10** [comment]
> 2. Add another column that identifies amortizable costs to make them easier to filter out.

Doesn't `PricingCategory` already do this?  Purchases and on-demand usage are `Standard` and amortized costs are `Committed`?

**Comment by kk09v** [comment]
At a minimum, we need to update the Use Case Library because these queries don't use `PricingCategory`
- Determine Effective Savings Rate by Service
- Determine Effective Savings Rate

**Comment by flanakin** [comment]
> > 2. Add another column that identifies amortizable costs to make them easier to filter out.
> 
> Doesn't `PricingCategory` already do this?  Purchases and on-demand usage are `Standard` and amortized costs are `Committed`?

Technically, someone can amortized a standard purchase. In that case, it's not.

**Comment by jpradocueva** [comment]
### Summary from the Maintainers' all on Nov 25
Context:
This work item addresses concerns about potential double-counting of costs in the presence of commitment discounts, aiming to provide robust guidance for accurate cost calculation.
Maintainers Assigned:
Michael, Riley 
Task Force Assigned:
Task Force 1 (TF1).

**Comment by flanakin** [comment]
Here's a proposed approach to how we address this:
1. Review design principles to see if it accounts for usability of aggregations
2. Brainstorm options in an offline meeting -- invite as broad of an audience as possible -- Some ideas might include:
   - Better documentation with no spec change
   - Column description changes only
   - Add a column to identify amortized purchases
   - Split ListCost and ContractedCost columns into billed and amortized variants
3. Run a survey for 1-2 weeks with a broad audience
4. Make the spec/doc changes based on the findings

**Comment by flanakin** [comment]
Options we brainstormed during the tail-end of a the TF1 call:
1. ~Better documentation outside the spec with no spec change (e.g., use case library)~
   - Cons:
     - No way to require providers to document their amortization scenarios
     - Requires practitioners to know (without documentation) which charges are amortized in order to craft a query
     - Practitioners will still run into the double-counting issue (and will likely not know they're seeing it)
   - NOTE: This isn't an option because we need to update cost/quantity columns to account for all amortized purchases
2. Column description changes only in the spec
   - Pros:
     - No spec change
   - Cons:
     - No way to require providers to document their amortization scenarios
     - Requires practitioners to know (without documentation) which charges are amortized in order to craft a query
     - Practitioners will still run into the double-counting issue (and will likely not know they're seeing it)
3. Add provider documentation requirement to the spec
   - Pros:
     - Explicitly documents scenarios where charges are being amortized
   - Cons:
     - Requires practitioners to review provider docs in order to craft a query
     - Practitioners will still run into the double-counting issue (and will likely not know they're seeing it)
4. Add a column to identify amortized purchases
   - Pros:
     - Explicitly calls out what charges ListCost and ContractedCost
   - Cons:
     - Practitioners may still run into the double-counting issue (and will likely not know they're seeing it)
5. Don't specify ListCost or ContractedCost for anything that is amortized
   - Pros:
     - Avoids practitioners from running into the double-counting problem ever
   - Cons:
     - Breaking change
     - Requires practitioners to use native datasets to calculate negotiated savings from amortized purchases
6. Split ListCost and ContractedCost columns into billed and amortized variants
   - Options:
     1. BREAKING: ListCost, ContractedCost, EffectiveListCost, EffectiveContractedCost
     2. BREAKING: BilledListCost, BilledContractedCost, EffectiveListCost, EffectiveContractedCost
     3. ListCost, ContractedCost, BilledListCost, BilledContractedCost, EffectiveListCost, EffectiveContractedCost
   - Pros:
     - Avoids practitioners from running into the double-counting problem ever
   - Cons:
     - May be a breaking change
     - Adds complexity with 2 new columns to differentiate billed and amortized versions of list/contracted cost

**Comment by jpradocueva** [comment]
### Action Items from the Members' call on December 5:
- [ ] [[#647](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/647)] Volunteers: Propose clear definitions for list costs and contracted costs, ensuring consistency across providers.
- [ ] [[#647](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/647)] Volunteers: Document specific scenarios where double-counting occurs for inclusion in the resolution process.
- [ ] [[#647](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/647)] Irena @ijurica : Review dependencies on normative requirement updates under #556 to ensure alignment.
- [ ] [[#647](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/647)] All members: Review and provide feedback on backward compatibility principles to inform the resolution of #647.

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on Jan 6:
- [ ] [#647] TF1 Team - Prioritize discussion on this issue in an upcoming meeting to determine a clear path forward.

**Comment by shawnalpay** [comment]
Per discussion in Jan 14 TF1:

> 1. Better documentation outside the spec with no spec change (e.g., use case library)
Not deemed feasible
> 2. Column description changes only in the spec
Possible option
> 3. Add provider documentation requirement to the spec
Not deemed feasible
> 4. Add a column to identify amortized purchases (e.g. the original charge that gets amortized (principal); the amortization of that original charge; things that are not amortized; potentially a fourth state that covers an amortized principal?)
Possible option
> 5. Don't specify ListCost or ContractedCost for anything that is amortized
Not deemed feasible
> 6. Split ListCost and ContractedCost columns into billed and amortized variants
Not deemed feasible

Definitely need to add a use case to the library with a query that makes it clear how to avoid double-counting amortizations
Chris: what's the use case query with a new column vs without a new column?

**Comment by flanakin** [comment]
FYI - I'm syncing with @JGrubb to possibly pick this one up.

**Comment by JGrubb** [comment]
I still like the option of just zeroing out the affected columns - listCost and contractedCost - for these line items that are amortized into other line items, however I fully believe y'all that you've workshopped this out and it's not feasible.

In that case:

Assuming my understanding is correct, the desired API to work around this problem of double counting would be something like 

`sumIf(listCost, isAmortized IS NOT FALSE)`

and this proposed column is just a simple boolean?  It would only appear on the the initial RI or other upfront purchases?

**Comment by flanakin** [comment]
@JGrubb The main downside of that is practitioners would lose visibility into the negotiated savings on amortized purchases.

But, yes, that's the basic idea. We've avoided Boolean columns so far. That's an option, tho.

**Comment by JGrubb** [comment]
I asked my employer's FP&A about the terminology we're using here, this was the feedback:

> You're describing a prepaid expense schedule as referred to in accounting.  This schedule typically tracks the following:
> - Prepayment (what you referred to as Principal): The initial amount prepaid.
> - Amortized Amount: The portion of the prepayment recognized as an expense in each period.
> - Accumulated Amortization: The total amount of the prepayment expensed to date.
> - Net Prepayment Amount: The remaining prepaid balance (Prepayment - Accumulated Amortization).
> - Expense Amount:  (Often the same as the amortized amount in a given period, but could differ in certain circumstances.) The expense recognized in the current period.
> - Accumulated Expense Amount: The total expense recognized to date.
> Each of the initial prepayment and the individual savings plan would have one of the above :point_up_2: applied to them.

It seems to me that "prepayment" and "amortized amount" are closer to what we're trying to convey here, and as a bonus "prepayment" requires no explanation to the finops practitioner.

Thoughts?

**Comment by shawnalpay** [comment]
In the Feb 11 TF1 call today, we discussed the possibility of expanding the scope of the column proposed in PR #747 to include telling the story of *resource coverage eligibility* as described in Work Item #406.  

This would potentially expand this column to carry four values instead of two:

1. `Commitment Purchase`: purchases of commitment discounts
2. `Eligible - Covered`: usage that was covered by a commitment discount
3. `Eligible - Not Covered`: usage that was not covered by a commitment discount _but could have been_ 
4. `Not Coverable`: usage that cannot be covered

This would not only allow the practitioner to avoid double-counting of costs, but it would also allow the practitioner to determine the universe of coverage, which would unlock the ability to calculate a meaningful `coverage %`.

@robmartin33 raised the good point that this would not tell the practitioner _which_ commitment discount types the resource is eligible for.  That would likely need to be a separate JSON column (i.e. list all commitment discount types with eligibility flags) in a future release.

@flanakin: particularly interested in your thoughts here, as the Maintainer sponsor of this Work Item.  Are you open to going down this road, given that TF1 today is interested?

**Comment by Matt-Cowsert** [comment]
The scope of this request is captured in #974. Closing this WI as it's no longer being used to track scope and development. WI is also captured within the supporting documentation of the related FR.
