### ISSUE TITLE
[FEEDBACK]: Clarifying "Reduced" vs "Negotiated" terminology

### ISSUE THREAD

**Issue by boblooney2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#662]
### Summary

FOCUS column library descriptions interchange "reduced" and "negotiated" terminology, but I believe they mean the same thing

### Which area does this issue relate to?

B: Existing FOCUS specification content

### Detailed Description

2 metrics use the term "Reduced rates": Billed Cost and Effective Cost

1 metric uses the term "Reduced price": Pricing Categories.  

4 metrics use the term "Negotiated Discounts": Commitment Discount Quantity, Commitment Discount Unit, Contracted Cost, Contracted Unit Price

I believe these terms are the same concept.  If so, I recommend aligning on 1 term ("negotiated" being my preference vs "reduced").  If they are not the same concept, some additional clarification of their differences would be helpful.  

It might also be worth considering fully defining the term "negotiated discounts" or "negotiated price" with some explicit AWS/Azure/GCP examples to be even more clear what this means given that the term is used to define other terms.

### What use cases, FinOps or others, can't be performed with the existing specification unless this issue is addressed?

absent clarity of definition, it could be hard for vendors and practitioners to audit these various metrics given the potential ambiguity their definitions introduce.

### Which FinOps personas does this issue relate to?

All

### Which provider groups or specific providers does this issue relate to?

Potentially all if the metric definitions aren't clear.

### On a scale of 1 - 4, how critical is this for your organization?

3: Important for adoption in the next 6-12 months

### Objective

enhanced documentation that provides additional clarity and is internally consistent

### Data Examples

https://focus.finops.org/focus-columns/

**Comment by flanakin** [comment]
I'm not looking at specific instances right now, but from memory, I believe "reduced" is used to indicate many types of cost/price reduction, like negotiated and commitment discounts. It's not just negotiated discounts alone. When we only talk about one, we should be using that specific discount type by name.

This is not to say that there isn't room for clarification and consistency. Just sharing what I recall in case it helps.

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on December 9:
- [ ] [[#662](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/662)] Irena @ijurica  to incorporate this issue into the normative requirements analysis under [#557](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/557).
- [ ] [[#662](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/662)] Chris @cnharris10  to provide examples of reduced and negotiated discounts for inclusion in the glossary.
- [ ] [[#662](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/662)] Riley @rileyjenk to draft examples of reduced and negotiated discounts for review.
- [ ] [[#662](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/662)] Irena @ijurica to include this terminology in the analysis for [#557](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/557).

**Comment by shawnalpay** [comment]
@ijurica Can you please analyze and determine what we should do from an editorial perspective here?

**Comment by Matt-Cowsert** [comment]
support moved over to #1074
