### ISSUE TITLE
[FEEDBACK]: New FOCUS column to track "associated" resource ID

### ISSUE THREAD

**Issue by boblooney2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#663]
### Summary

Several cloud resources interact with or rely on other resources.  This data is insightful and potentially useful for things like cost allocation or total cost analysis.

### Which area does this issue relate to?

A: Missing FinOps feature, use case, or scenario

### Detailed Description

There are several concepts where cloud resources that are associated with other cloud resources.  

One common example is a disk resource, NIC resource, and Public IP resource being associated with a virtual machine.  To see the total cost of a VM, you would want to pull together all of these pieces.

A second example is a snapshot or backup being associated with a disk.

A more complex example is an App (which does not bear a cost) running on a costed resource, but the app information is more appropriate for cost allocation.  The lack of the relationship between the apps and where the cost occurs hinders this sort of allocation.

An example from the SaaS world - In Snowflake, a database is acted on by a compute resource.  The compute is where the cost lands and "uses" credits.  There isn't currently a mechanism to associate that compute acting on a specific database or being used by a specific user account - either of which could be useful for cost allocation.

### What use cases, FinOps or others, can't be performed with the existing specification unless this issue is addressed?

The most straightforward use case is reporting on total cost of a cloud resource like a VM.  If you can't chain all the various costed resources to the top level parent resource, you're only seeing a slice of the cost of that resource.

### Which FinOps personas does this issue relate to?

Allocation and analytical reports driving off this enhanced information would have an impact across all personas

### Which provider groups or specific providers does this issue relate to?

All CSPs; SaaS;

### On a scale of 1 - 4, how critical is this for your organization?

3: Important for adoption in the next 6-12 months

**Comment by jpradocueva** [comment]
### Action Items from the Maintainers' call on December 9:
- [ ] [[#663](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/663)] Karl to document findings from the ad-hoc meeting on SKU properties and assess their relevance to resource ID relationships.
- [ ] [[#663](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/663)] Karl @kk09v to explore related use cases and provide a summary of resource relationship challenges.
- [ ] [[#663](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/663)] Chris @cnharris10 to draft potential schemas for representing parent-child or associated resource relationships.

**Comment by shawnalpay** [comment]
@Matt-Cowsert Please stand up a Feature Request for this, and please partner with @boblooney2 if you have any questions!

**Comment by Matt-Cowsert** [comment]
support captured on #1075
