### ISSUE TITLE
[Proposal] Create a generalized shared cost billing model

### ISSUE THREAD

**Issue by cnharris10** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#72]
### Type
> Metrics / Dimensions

### Proposed Change
> Provide a normalized spec for exposing software-defined allocated costs that easily tie these costs to corresponding virtual or dedicated hardware. 

### Context / Supporting information
> There exists service-based costs and rollups in AWS’ CUR and GCP GKE cost datasets but there does not exist an overarching, normalized model for representing service-based cost allocation nor attribution to corresponding virtual or dedicated hardware.

Given numerous orchestrators and their similar operating models (allocating subset of resources as processing entities), there must be a generalized model proposed.

**Comment by udam-f2** [comment]
@cnharris10 Could you please chase this down and see if this should become a work item or a discussion topic?

**Comment by jpradocueva** [comment]
@cnharris10 The group asked for further information during the TF-1 call on May 28.

**Comment by AWS-ZachErdman** [comment]
I'm interested in this one for v1.1

**Comment by salpaysenturus** [comment]
Some context for the AWS and GCP implementations of this idea:

https://docs.aws.amazon.com/cur/latest/userguide/split-cost-allocation-data.html
https://cloud.google.com/kubernetes-engine/docs/how-to/cost-allocations

Would the scope of this be only for containers, or would we be looking to expand it beyond that to include any service with usage-based breakdowns?  For example, here's a bunch of hoops one can jump through to allocate shared Fabric costs.  Painful, but super important for allocation purposes.

https://pbi-guy.com/2024/03/30/how-to-extract-data-from-the-fabric-metrics-app-part-1/

**Comment by cnharris10** [comment]
> Some context for the AWS and GCP implementations of this idea:
> 
> https://docs.aws.amazon.com/cur/latest/userguide/split-cost-allocation-data.html
> https://cloud.google.com/kubernetes-engine/docs/how-to/cost-allocations
> 
> Would the scope of this be only for containers, or would we be looking to expand it beyond that to include any service with usage-based breakdowns?  For example, here's a bunch of hoops one can jump through to allocate shared Fabric costs.  Painful, but super important for allocation purposes.
> 
> https://pbi-guy.com/2024/03/30/how-to-extract-data-from-the-fabric-metrics-app-part-1/

AWS supports tasks (ECS), pods (EKS), and jobs (Batch). I'd hope we could solve generally various orchestration systems: K8s, EMR, Dataproc/Dataflow, Spark, Flink, etc.

**Comment by shawnalpay** [comment]
Discussed in Oct 22 TF1 call.  Need to talk about this one a little bit more to align on scope: is it just orchestration and/or container services, or is it more holistic than that?  This is a big conceptual topic, and I believe Chris' proposal is sticking to a narrow scope for 1.2 -- but let's discuss more in calls to ensure that everyone understands the overall concept.

**Comment by richwang99** [comment]
K8S is taking more and more weightage for the Cloud costs (passing the 50% mark). Better breaking down of those costs is becoming essential.

**Comment by shawnalpay** [comment]
In the Oct 29 TF1 call today, we discussed revising the scope of this `Work Item` to be able to generically handle not only for compute clusters (e.g. AWS [ECS](https://docs.aws.amazon.com/cur/latest/userguide/split-cost-allocation-data.html), GCP [GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/cost-allocations)), but also other types of services that can be allocated (e.g. OCI [pluggable databases](https://docs.oracle.com/en-us/iaas/releasenotes/billing/costanalysis-vmclusterpluggabledb.htm)), as well as any other services that may be attributed down the road.  This would holistically handle for the use case of `Consume allocated costs as calculated by the provider`.  @cnharris10, do you agree with this approach, and if so, are you amenable to revising this `Work Item` to reflect that?  Happy to huddle and discuss if you like.

FYI that we also discussed a net-new `Work Item` to handle for a separate but related use case of `Consume usage metrics that facilitate cost allocations as calculated by the practitioner`, which would like result in supporting content rather than a spec change, and which @ahullah and @tobrien will craft.

**Comment by cnharris10** [comment]
The intention of this work item is to classify an approach for similar shared allocation models.  If "compute" is too narrow and can expanded to other examples that closely relate, then I'm in support.

**Comment by jpradocueva** [comment]
### Action Items from TF-1 call on Oct 29:
- [ ] [[#72](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/72)] Alex @ahullah  & Tim @tobrien : Draft a work item detailing concepts for future holistic allocation patterns beyond computing clusters.
- [ ] [[#72](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/72)] Chris @cnharris10  & Shawn @shawnalpay : Expand the current work item to outline patterns for generic cost allocation across cloud services, ensuring the scalability of new services as they emerge.

**Comment by shawnalpay** [comment]
@cnharris10 I have now modified this `Work Item` to more holistically include all provider-generated shared cost allocations, not just compute clusters.  Give it a look and let me know if it looks alright to you.

**Comment by jpradocueva** [comment]
### Action Items from Members' call on Oct 31:
- [ ] [[#72](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/72)] Alex @ahullah  and Tim @tobrien : Revise the work item to specify use cases and align it with provider-focused data.
- [ ] [[#72](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/72)] All TF1 members: Review the draft for shared cost allocation and provide feedback on proposed divisions

**Comment by ljadvey** [comment]
What about direct cost allocation (not shared)?  Allocation vision and strategy in general with FOCUS needs to be discussed

**Comment by jpradocueva** [comment]
### Action Items from the TF-1 call on November 5:
- [ ] [[#638](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/368)] Alex @ahullah : Augment #638 to clarify artifact expectations, focusing on FOCUS-specific data and outputs for practitioner allocations.
- [ ] [[#72](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/72)] Team: Continue discovering existing provider data structures to understand viable FOCUS configurations for split costs.

**Comment by jpradocueva** [comment]
### Comments from the Members' call on November 7:
[#72](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/72): TF-1 is working on cost allocation strategies for multi-provider models, addressing cases where multiple resources feed into a single service element, such as clustered resources. The current focus is on allowing providers to share their allocation metadata within the specification.

**Comment by Matt-Cowsert** [comment]
closing this WI as we've delivered split cost allocation for provider-defined services in the 1.3 development cycle.
